from cardkit import S, combo, match, tf, mc

MOD = 5
TM = "Translation Machinery & Genetic Code"
TP = "Translation Stages: Prok vs Euk"
SO = "Regulation & Protein Sorting"

CARDS = [
# ───────────────────────── Translation Machinery & Genetic Code ─────────────────────────
combo(TM, "From gene to anticodon",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> The four rows show one codon's worth of a gene, its mRNA and the tRNA that reads it.<br><br><b>(나)</b> Unlabelled sequences are written 5'→3'.",
  [S("Written in the standard 5'→3' direction, the anticodon is UGC.", True,
     "The anticodon is 3'-CGU-5'; read from its 5' end it is 5'-UGC-3'."),
   S("The anticodon has the same sequence and orientation as the DNA template strand, except that it has U where the template has T.", True,
     "The template strand and the anticodon are both complementary to the codon, so they match base for base (3'-CGT-5' vs 3'-CGU-5'), with U in RNA where DNA has T."),
   S("The mRNA is copied from the nontemplate strand, which is why their sequences match.", False,
     "RNA polymerase reads the template strand. The mRNA matches the nontemplate strand only because both are complementary to the template (Module 4).")],
  "Codon–anticodon pairing is antiparallel · Template vs nontemplate strand (Module 4)",
  ["codon_anticodon_antiparallel", "trna_adapter_structure", "m4_template_coding_strands"],
  points=3, diagram="trna_codon_pairing"),

tf(TM, "In the diagram, the middle base of the DNA template strand (G) is mutated to A. (GCA = Ala, GUA = Val, GAA = Glu)",
  "The mRNA codon becomes GUA, so the protein carries valine in place of alanine.",
  True,
  "The template's middle base pairs with the codon's middle base. Template G → A means the mRNA gets U instead of C: GCA becomes GUA, which codes for Val. One base change in the gene, one amino acid change in the protein.",
  "Template strand → codon → amino acid",
  ["codon_triplet_nonoverlapping", "central_dogma_translation_final", "m4_template_coding_strands"],
  points=2, diagram="trna_codon_pairing"),

mc(TM, "Using the genetic code table, which single-base change in the mRNA codon CUU would NOT change the amino acid?",
  "CUU → CUC",
  ["CUU → CCU",
   "CUU → AUU",
   "CUU → CAU",
   "CUU → UUU"],
  "CUU and CUC both code for Leu. The others give Pro (CCU), Ile (AUU), His (CAU) and Phe (UUU). Third-position changes are the ones most often silent, because the code is redundant: many amino acids have codons that differ only in their third base.",
  "Redundancy of the genetic code · Silent changes",
  ["genetic_code_64_redundant", "codon_triplet_nonoverlapping"],
  points=1, diagram="genetic_code_table"),

tf(TM, "Using the genetic code table, count the codons for each amino acid.",
  "Every amino acid is encoded by at least two codons, which is what makes the code redundant.",
  False,
  "Methionine (AUG) and tryptophan (UGG) each have only one codon. The code is still redundant because most amino acids have two to six codons: 61 coding codons for 20 amino acids.",
  "Redundancy of the genetic code · AUG start codon",
  ["genetic_code_64_redundant", "start_stop_codons"],
  points=1, diagram="genetic_code_table"),

mc(TM, "Using the genetic code table, a ribosome starts at the first AUG of the mRNA 5'-CCAUGGUUCAUUGAGC-3'. What polypeptide is made?",
  "Met–Val–His (3 amino acids)",
  ["Met–Val–His–Trp (4 amino acids)",
   "Pro–Trp–Phe–Ile–Glu (5 amino acids)",
   "Met–Val (2 amino acids)",
   "Met–Val–His–Stop (4 amino acids)"],
  "Starting at AUG sets the reading frame: AUG (Met) GUU (Val) CAU (His) UGA (stop). A stop codon has no amino acid (and UGA is not UGG, Trp), so the chain is 3 long. Reading from the first base would give a different frame (CCA UGG UUC…) and a different protein.",
  "Start codon sets the reading frame · Stop codons",
  ["start_stop_codons", "reading_frame", "codon_triplet_nonoverlapping"],
  points=2, diagram="genetic_code_table"),

mc(TM, "Which mutation in the middle of a gene's coding sequence is least likely to destroy the protein's function?",
  "Deleting the three nucleotides of one whole codon",
  ["Deleting a single nucleotide from the middle of a codon",
   "Inserting two nucleotides between two codons",
   "Inserting one nucleotide just after the start codon",
   "Changing one codon in the middle to UAA"],
  "Codons are read three at a time from the start codon. Removing one whole codon deletes one amino acid but keeps the reading frame, so everything downstream is unchanged. Adding or removing 1 or 2 nucleotides shifts the frame and garbles every later codon, and UAA ends the chain early.",
  "Reading frame · Nonoverlapping triplets · Stop codons",
  ["reading_frame", "codon_triplet_nonoverlapping", "start_stop_codons"],
  points=2),

combo(TM, "Freeze-frame on a ribosome",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> UGG codes for Trp and AAA for Lys; UAG is a stop codon.<br><br><b>(나)</b> The ribosome will keep translating this mRNA until the polypeptide is finished.",
  [S("The incoming tRNA marked ? must carry the anticodon 3'-ACC-5' and the amino acid Trp.", True,
     "The A site holds codon 5'-UGG-3'; its antiparallel partner is 3'-ACC-5', and the tRNA with that anticodon is charged with Trp."),
   S("The finished polypeptide will be Met–Ala–Trp–Lys, with Met at its N-terminus.", True,
     "AUG GCU UGG AAA, then UAG (stop): Met–Ala–Trp–Lys. Met, the first amino acid, keeps the free amino group."),
   S("The tRNA in the E site is uncharged and is about to leave the ribosome.", True,
     "It delivered Met, passed it on when the first peptide bond formed, and now exits empty from the E site.")],
  "A, P and E sites · Codon–anticodon pairing · Start and stop codons",
  ["ribosome_a_p_e_sites", "codon_anticodon_antiparallel", "start_stop_codons", "n_terminus_c_terminus"],
  points=3, diagram="ribosome_snapshot"),

mc(TM, "In the diagram, which way is the ribosome moving along the mRNA, and how can you tell?",
  "Toward 3': the start codon AUG has already moved into the E site",
  ["Toward 5': tRNA anticodons are written 3'→5'",
   "Toward 5': Met at the chain's free end was the last amino acid added",
   "Toward 3': the large subunit always sits on the mRNA's 3' side",
   "It stays put while the mRNA slides back and forth through it"],
  "Ribosomes read mRNA 5'→3'. The start codon AUG — read first — is already in the E site, and the unread codons lie on the 3' side. Met at the chain's free end was the first amino acid added, not the last, which also shows the ribosome began at the 5' end.",
  "Ribosomes move 5'→3' · A, P and E sites · The N-terminus is made first",
  ["ribosome_moves_5_to_3", "ribosome_a_p_e_sites", "n_terminus_c_terminus"],
  points=2, diagram="ribosome_snapshot"),

tf(TM, "In a classic experiment, the cysteine already attached to a charged tRNA-Cys was chemically converted to alanine, leaving the tRNA's anticodon unchanged. The tRNA was then added to a protein-making system.",
  "Alanine was inserted wherever the mRNA had a cysteine codon, because the ribosome checks only codon–anticodon pairing, not which amino acid the tRNA carries.",
  True,
  "tRNAs are adapters: the anticodon reads the codon, and the amino acid simply rides along. That's why the accuracy of aminoacyl tRNA synthetases, which load each tRNA with the right amino acid, matters so much.",
  "tRNAs as adapters · Accuracy depends on tRNA synthetases",
  ["trna_adapter_structure", "aminoacyl_trna_synthetase_charging", "codon_anticodon_antiparallel"],
  points=2),

tf(TM, "A cell runs short of free leucine, so many tRNAs whose anticodons read leucine codons stay uncharged.",
  "Ribosomes can skip the leucine codons and keep going in frame, making shorter proteins that lack leucine.",
  False,
  "An uncharged tRNA has no amino acid to deliver. A ribosome that reaches a leucine codon waits, with that codon in its A site, until a charged tRNA arrives; it doesn't skip codons.",
  "Charged vs uncharged tRNA · The A site",
  ["aminoacyl_trna_synthetase_charging", "ribosome_a_p_e_sites"],
  points=2),

match(TM, "Which component is responsible?",
  "Match each observation to the translation component that best explains it.",
  "Observation", "Component",
  [("A tRNA with a mutated anticodon inserts its amino acid at the wrong codons", "The tRNA's anticodon"),
   ("A tRNA is loaded with the wrong amino acid but still pairs with the correct codon", "An aminoacyl tRNA synthetase"),
   ("An antibiotic binds rRNA in the large subunit and blocks peptide bond formation", "The peptidyl transferase center"),
   ("In an extract missing one protein, finished chains stay attached to tRNAs at stop codons", "The release factor"),
   ("A human mRNA without a 5' cap isn't translated in a human cell extract", "Initiation factors that assemble at the cap")],
  "Each component has one job: the anticodon reads codons; synthetases load the right amino acid; the rRNA peptidyl transferase center joins amino acids; release factors free the finished chain at a stop codon; eukaryotic initiation factors bring the small subunit to the 5' cap.",
  "Components of translation",
  ["translation_components", "trna_adapter_structure", "aminoacyl_trna_synthetase_charging", "elongation_steps_peptidyl_transferase", "termination_release_factor", "euk_initiation_cap_scanning"],
  points=3),

mc(TM, "The standard genetic code has 64 codons. How many of them are read by tRNAs carrying an amino acid?",
  "61",
  ["64",
   "20",
   "60",
   "63"],
  "Three codons (UAA, UAG, UGA) are stop codons: no tRNA reads them, and a release factor binds instead. That leaves 61 codons for 20 amino acids, so most amino acids have several codons.",
  "Stop codons · A redundant code",
  ["start_stop_codons", "genetic_code_64_redundant", "termination_release_factor"],
  points=1),

tf(TM, "Suppose codons overlapped, so that bases 1-2-3, then 2-3-4, then 3-4-5 were each read as a codon.",
  "A single base change could then alter up to three neighbouring amino acids, whereas in the real code it alters at most one.",
  True,
  "In an overlapping code each base belongs to three codons. Real codons are a nonoverlapping series of triplets, so each base sits in exactly one codon, and a base change can affect only that codon's amino acid.",
  "Nonoverlapping triplets",
  ["codon_triplet_nonoverlapping"],
  points=2),

mc(TM, "Which RNAs are made by transcription but never translated into protein?",
  "tRNA and rRNA",
  ["mRNA and tRNA",
   "mRNA only",
   "rRNA and mRNA",
   "tRNA only"],
  "Only mRNA carries a code that ribosomes translate. tRNA and rRNA are noncoding RNAs: they're transcribed from DNA (rRNA in the nucleolus) and work as RNA — tRNA as the adapter, rRNA as the ribosome's structural and catalytic core.",
  "Central dogma · Noncoding RNAs · Ribosomes are RNA + protein",
  ["central_dogma_translation_final", "ribosome_rna_protein_subunits", "gene_expression_overview_euk", "m4_rna_types"],
  points=1),

tf(TM, "Translation is the last step in the flow of information from DNA to protein.",
  "Given a protein's amino acid sequence, you could work out the exact mRNA sequence that coded for it.",
  False,
  "The code is redundant: most amino acids have two to six codons, so one protein sequence fits many possible mRNAs. Information can be read from codon to amino acid, but not reconstructed exactly the other way.",
  "Redundancy of the code · Central dogma",
  ["central_dogma_translation_final", "genetic_code_64_redundant"],
  points=2),

tf(TM, "A student is asked for the anticodon that pairs with the mRNA codon 5'-AUG-3'.",
  "Pairing base by base gives UAC, so written 5'→3' the anticodon is 5'-UAC-3'.",
  False,
  "Pairing is antiparallel: the codon's first (5') base pairs with the anticodon's last (3') base. The anticodon is 3'-UAC-5', which written 5'→3' is 5'-CAU-3'.",
  "Codon–anticodon pairing is antiparallel",
  ["codon_anticodon_antiparallel"],
  points=1),

# ───────────────────────── Translation Stages: Prok vs Euk ─────────────────────────
combo(TP, "Where can a ribosome start?",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> Each coding bar is read from its AUG to the stop codon that follows.<br><br><b>(나)</b> The inner AUG of mRNA 1 lies in the same reading frame as its first AUG.",
  [S("mRNA 2 can yield three separate polypeptides, because a ribosome can begin at each AGGAGGU sequence.", True,
     "Each coding region has its own Shine-Dalgarno sequence (AGGAGGU) upstream of its AUG, so one bacterial mRNA can code for several polypeptides."),
   S("On mRNA 1, translation starts at the first AUG after the cap, and the inner AUG is read as methionine within the same polypeptide.", True,
     "The initiation complex assembles at the 5' cap and scans to the first AUG; a later AUG in the same frame simply codes for Met inside the chain."),
   S("mRNA 1 comes from a bacterium, since it ends in a tail of A's.", False,
     "A 5' cap and a poly(A) tail are eukaryotic processing marks (Module 4). Bacterial mRNAs have no cap; mRNA 2's Shine-Dalgarno sequences mark it as bacterial.")],
  "Cap and scanning vs Shine-Dalgarno · Polycistronic mRNA",
  ["prok_initiation_shine_dalgarno", "polycistronic_mrna", "euk_initiation_cap_scanning", "start_stop_codons", "m4_mrna_processing_cap_tail_splicing"],
  points=3, diagram="translation_start_prok_euk"),

tf(TP, "A researcher deletes only the first AGGAGGU sequence of mRNA 2 in the diagram.",
  "The first polypeptide stops being made, while the second and third are still translated.",
  True,
  "In bacteria, each coding region's own Shine-Dalgarno sequence recruits a ribosome, which starts at the next AUG. Removing the first one blocks only the first region; the other two keep their binding sites.",
  "Shine-Dalgarno sequence · Polycistronic mRNA",
  ["prok_initiation_shine_dalgarno", "polycistronic_mrna"],
  points=2, diagram="translation_start_prok_euk"),

tf(TP, "mRNA 1 in the diagram is added to a bacterial extract containing bacterial ribosomes and translation factors, but no eukaryotic initiation factors.",
  "The bacterial ribosomes can bind the cap and start translating at mRNA 1's first AUG.",
  False,
  "Bacterial ribosomes find start sites by pairing with Shine-Dalgarno sequences, not caps, and mRNA 1 has none. That's why genes moved into bacteria are given a bacterial ribosome-binding sequence upstream of the AUG.",
  "Shine-Dalgarno vs cap-dependent initiation",
  ["prok_initiation_shine_dalgarno", "euk_initiation_cap_scanning", "translation_components"],
  points=2, diagram="translation_start_prok_euk"),

mc(TP, "Put these events of eukaryotic translation in order: (1) the large subunit joins; (2) the small subunit, initiation factors and Met-tRNA bind at the 5' cap; (3) the complex scans to the first AUG; (4) the first peptide bond forms.",
  "2 → 3 → 1 → 4",
  ["3 → 2 → 1 → 4",
   "2 → 1 → 3 → 4",
   "1 → 2 → 3 → 4",
   "2 → 3 → 4 → 1"],
  "The small subunit with Met-tRNA and initiation factors loads at the cap and scans; only when it reaches AUG does the large subunit join (and the factors leave). Peptide bonds form in the large subunit, so the first one comes last.",
  "Eukaryotic initiation · Stages of translation",
  ["euk_initiation_cap_scanning", "translation_three_stages", "elongation_steps_peptidyl_transferase"],
  points=2),

tf(TP, "In the diagram, Met–Ala is attached to the tRNA in the P site, and a charged tRNA now enters the A site.",
  "When the next peptide bond forms, the new amino acid is added onto the chain, which stays attached to the P-site tRNA.",
  False,
  "The reverse: the whole chain is transferred from the P-site tRNA onto the amino acid carried by the A-site tRNA. The chain (now Met–Ala–Trp) hangs from the A-site tRNA until the ribosome shifts one codon and moves that tRNA into the P site.",
  "Elongation: transfer to the A-site tRNA · Translocation",
  ["elongation_steps_peptidyl_transferase", "translocation_one_codon", "ribosome_a_p_e_sites"],
  points=2, diagram="ribosome_snapshot"),

mc(TP, "In the diagram, a tRNA enters the A site, a peptide bond forms, and the ribosome then shifts one codon. Which codons now sit in the E, P and A sites?",
  "E: GCU, P: UGG, A: AAA",
  ["E: AUG, P: GCU, A: UGG",
   "E: UGG, P: AAA, A: UAG",
   "E: ACC, P: AUG, A: GCU",
   "E: GCU, P: UGG, A: UAG"],
  "Translocation moves the ribosome one codon toward the 3' end: the tRNA on UGG (now holding the chain) moves to P, the empty tRNA on GCU moves to E, and the next codon, AAA, enters the A site.",
  "Translocation by one codon · Ribosomes move 5'→3'",
  ["translocation_one_codon", "ribosome_moves_5_to_3", "ribosome_a_p_e_sites"],
  points=2, diagram="ribosome_snapshot"),

combo(TP, "Endgame for this mRNA",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> The ribosome continues along the mRNA until it reaches UAG.<br><br><b>(나)</b> No tRNA has an anticodon that pairs with UAG.",
  [S("When UAG reaches the A site, a release factor protein binds there instead of a tRNA.", True,
     "Stop codons are recognized by a protein release factor, not by a tRNA."),
   S("The chain is freed by breaking the peptide bond between its last two amino acids.", False,
     "Release breaks the bond between the finished chain and the tRNA holding it. All peptide bonds stay intact, and the last amino acid's carboxyl group becomes the C-terminus."),
   S("The ribosome will translate GCA, the codon after UAG, as alanine before it lets go.", False,
     "Translation ends at the stop codon; codons beyond it, such as GCA, aren't read.")],
  "Termination: release factor · Stop codons · C-terminus",
  ["termination_release_factor", "start_stop_codons", "n_terminus_c_terminus"],
  points=3, diagram="ribosome_snapshot"),

tf(TP, "Translation initiation differs between bacteria and eukaryotes.",
  "Elongation and termination differ just as much, since bacterial ribosomes lack A, P and E sites.",
  False,
  "The differences are in initiation (cap and scanning vs Shine-Dalgarno sequences). Both kinds of ribosome have A, P and E sites, and elongation and termination work the same way.",
  "Elongation and termination are shared",
  ["elongation_termination_conserved", "ribosome_a_p_e_sites"],
  points=1),

tf(TP, "Electron micrographs often show several ribosomes spaced along one mRNA at the same time.",
  "Each ribosome makes only part of the polypeptide, and the pieces are joined together afterward.",
  False,
  "Each ribosome starts at the start codon and runs to the stop codon, making its own complete chain. Several ribosomes on one mRNA simply make several copies at once.",
  "Many ribosomes per mRNA · Ribosomes read 5'→3'",
  ["gene_expression_overview_euk", "ribosome_moves_5_to_3", "translation_three_stages"],
  points=1),

tf(TP, "A mutation creates an extra AUG in the 5' untranslated region of a human mRNA, between the cap and the normal start codon, in a different reading frame.",
  "Scanning ribosomes can start at this new AUG instead, making a short, wrong polypeptide and less of the normal protein.",
  True,
  "Eukaryotic ribosomes start at the first AUG they reach while scanning from the cap. An upstream AUG in another frame diverts them into the wrong reading frame — a known cause of some inherited diseases.",
  "Scanning from the cap · Reading frame",
  ["euk_initiation_cap_scanning", "reading_frame"],
  points=2),

tf(TP, "A drug blocks only one step of translation: the large ribosomal subunit joining the small subunit at the start codon.",
  "Ribosomes already partway along an mRNA when the drug is added will finish their proteins, but no new proteins will be started.",
  True,
  "Joining of the large subunit is part of initiation. Ribosomes already in elongation don't need that step again, so they run on to the stop codon; new rounds of initiation are blocked.",
  "Three stages of translation",
  ["translation_three_stages", "euk_initiation_cap_scanning"],
  points=2),

mc(TP, "A mutation changes codon 40 of a gene's 300 codons (counting AUG as codon 1) into UAG. What does the cell make from this mRNA?",
  "A 39-amino-acid chain, freed when a release factor binds UAG",
  ["A full-length chain lacking only its 40th amino acid",
   "A 40-amino-acid chain ending in a special stop amino acid",
   "No chain at all, since translation can't begin",
   "A full-length chain, since a tRNA reads UAG as an amino acid"],
  "Codons 1–39 are translated normally. UAG in the A site is recognized by a release factor (no tRNA reads it), so a shortened 39-amino-acid chain is released — usually nonfunctional.",
  "Stop codons · Termination by release factor",
  ["termination_release_factor", "start_stop_codons"],
  points=2),

match(TP, "Where does it happen?",
  "Match each event to where it happens.",
  "Event", "Where",
  [("A charged tRNA first pairs with its codon", "The A site"),
   ("The tRNA holding the growing chain waits for the next amino acid", "The P site"),
   ("An uncharged tRNA leaves the ribosome", "The E site"),
   ("A eukaryotic ribosome first assembles on an mRNA", "The 5' cap"),
   ("A bacterial ribosome first binds an mRNA", "AGGAGGU, upstream of an AUG")],
  "A = aminoacyl-tRNA entry, P = peptidyl-tRNA, E = exit. Eukaryotic initiation begins at the 5' cap and scans to AUG; bacterial ribosomes bind Shine-Dalgarno sequences (AGGAGGU) just upstream of each AUG.",
  "A, P and E sites · Initiation in eukaryotes vs bacteria",
  ["ribosome_a_p_e_sites", "euk_initiation_cap_scanning", "prok_initiation_shine_dalgarno"],
  points=3),

# ───────────────────────── Regulation & Protein Sorting ─────────────────────────
combo(SO, "Four snapshots at the ER",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> Panels 1–4 follow one ribosome making one protein.<br><br><b>(나)</b> In panel 1, the SRP is bound to the signal sequence as it emerges from the ribosome.",
  [S("Translation pauses while the SRP is bound and resumes once the ribosome is handed to the channel.", True,
     "The SRP halts translation until the ribosome docks at the ER; when the SRP lets go, synthesis resumes and the chain is threaded through the channel."),
   S("The signal sequence lies at the protein's amino end, since it is the first part of the chain to emerge from the ribosome.", True,
     "Chains are made N-terminus first, so an amino-terminal signal is the first segment out — early enough to be caught before the protein is finished."),
   S("Because the protein in panel 4 is in the ER lumen, it can only ever stay inside the ER.", False,
     "From the lumen, a protein may stay in the ER, travel in vesicles to another organelle's lumen (such as the Golgi or a lysosome), or be secreted (Module 3).")],
  "SRP targeting · Fates of rough-ER proteins (Module 3)",
  ["srp_er_targeting", "rough_er_protein_fates", "n_terminus_c_terminus", "m3_endomembrane_secretory_route"],
  points=3, diagram="srp_targeting_steps"),

mc(SO, "In a mutant cell the SRP receptor is missing, but the SRP and the signal sequence are normal. What happens to a protein destined for secretion?",
  "SRP still binds and pauses synthesis, but the ribosome can't dock at the ER",
  ["The SRP can't bind the signal sequence, so translation never pauses",
   "The protein enters the ER normally, since the channel alone recognizes the signal",
   "The protein enters the ER, but its signal sequence is never removed",
   "The protein is redirected to the mitochondria by its signal sequence"],
  "The SRP recognizes the signal and halts translation, but docking requires the SRP receptor on the ER membrane. Without it, the ribosome is never handed to the channel, so the protein doesn't enter the ER or follow the secretory route.",
  "SRP and SRP receptor · Translation starts in the cytosol",
  ["srp_er_targeting", "translation_starts_cytosol"],
  points=2, diagram="srp_targeting_steps"),

tf(SO, "A secretory protein's gene is altered so that its ER signal sequence is deleted; nothing else changes.",
  "The protein will be made on free ribosomes and stay in the cytosol, since the SRP has nothing to recognize.",
  True,
  "Translation always begins in the cytosol. Without a signal, the SRP never binds and the ribosome never goes to the ER; a protein with no signal remains in the cytosol.",
  "No signal → cytosol · SRP needs the signal sequence",
  ["sorting_signals_destinations", "srp_er_targeting", "translation_starts_cytosol"],
  points=1),

tf(SO, "Panel 4 of the diagram shows the signal sequence as a separate fragment near the channel.",
  "So the mature protein in the lumen has lost amino acids from its carboxyl (C-terminal) end.",
  False,
  "The signal sequence is the first part of the chain made, so it sits at the amino (N-terminal) end; cutting it off removes amino acids from the N-terminus. The mature protein is shorter than the chain the ribosome made.",
  "Signal sequence at the N-terminus · Cleavage in the ER",
  ["srp_er_targeting", "n_terminus_c_terminus"],
  points=1, diagram="srp_targeting_steps"),

combo(SO, "Which end faces out?",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> The protein's orientation in the ER membrane is set while it is being made.<br><br><b>(나)</b> It reaches the plasma membrane in vesicles that bud from one membrane and fuse with the next.",
  [S("In the right panel, the NH3+ end lies in the extracellular fluid.", True,
     "Budding and fusion never flip a membrane: the side facing the ER lumen stays inside the vesicles and faces outside the cell after fusion (Module 3). So the N-terminus, in the lumen, ends up outside."),
   S("The signal-anchor segment stays in the membrane because its side chains are mostly charged and cling to the phosphate heads.", False,
     "A segment spanning the membrane sits among the lipid tails, so its side chains are mostly nonpolar — the feature that marks integral membrane proteins (Module 3)."),
   S("Vesicle traffic turns the protein over, so the COO- end ends up outside the cell.", False,
     "Vesicles keep a protein's orientation: the COO- end, in the cytosol at the ER, stays in the cytosol at the plasma membrane.")],
  "Signal-anchor sequence · The lumen side becomes the outside (Module 3)",
  ["signal_anchor_membrane_protein", "rough_er_protein_fates", "m3_lumen_topology", "m3_membrane_protein_types"],
  points=3, diagram="signal_anchor_orientation"),

tf(SO, "Many plasma-membrane receptors carry sugar chains, which are attached in the lumen of the ER and Golgi.",
  "On the protein in the diagram, sugar chains attached in the ER lumen would end up on the NH3+ end's side of the membrane, outside the cell.",
  True,
  "Sugars are added to the part of the protein facing the lumen — the NH3+ end's side. Through vesicle traffic that side becomes the outside face of the plasma membrane, which is why glycoprotein sugars face outward.",
  "Membrane protein orientation · Glycoproteins face outward (Module 3)",
  ["signal_anchor_membrane_protein", "m3_lumen_topology", "m3_endomembrane_secretory_route"],
  points=2, diagram="signal_anchor_orientation"),

match(SO, "Address labels",
  "Match each protein to the sorting signal it needs.",
  "Protein", "Sorting signal",
  [("A glycolysis enzyme that works in the cytosol", "No signal sequence"),
   ("A citric acid cycle enzyme in the mitochondrial matrix", "An amino-terminal signal for organelle import (made on free ribosomes)"),
   ("A DNA polymerase that copies chromosomes", "An internal signal sequence"),
   ("Insulin, a hormone secreted by pancreatic cells", "An SRP-recognized ER signal alone; the chain ends up free in the lumen"),
   ("A receptor that spans the plasma membrane", "An ER signal plus a signal-anchor sequence that keeps it in the membrane")],
  "Where a protein works decides its label: none for the cytosol; an amino-terminal signal for mitochondria or chloroplasts; an internal signal for the nucleus; an SRP-recognized amino-terminal signal for the ER and secretory route; plus a signal-anchor sequence to stay in a membrane.",
  "Signal sequences and destinations",
  ["sorting_signals_destinations", "srp_er_targeting", "signal_anchor_membrane_protein", "translation_starts_cytosol"],
  points=3),

mc(SO, "Stomach cells secrete pepsin as an inactive precursor, pepsinogen, which becomes active only after part of its chain is cut off in the acidic stomach. Which level of gene-expression control does this illustrate?",
  "Post-translational modification",
  ["DNA accessibility",
   "Transcription factors",
   "RNA processing",
   "Translation initiation at the cap"],
  "The protein is already made; activating it by cutting the chain is a post-translational modification. Making it inactive protects the cells that produce it from digesting their own proteins.",
  "Post-translational modification · Real-world: digestive enzymes",
  ["post_translational_modification", "gene_expression_regulation_levels"],
  points=1),

tf(SO, "A liver cell and a neuron from the same person carry the same genes but make very different sets of proteins.",
  "This is possible because the two cell types can read their genes with different genetic codes.",
  False,
  "Both use the same standard code. They differ in which genes are expressed and how much, controlled at several levels: DNA accessibility, transcription factors, RNA processing and post-translational modification.",
  "Levels of gene regulation · One genetic code",
  ["gene_expression_regulation_levels", "genetic_code_64_redundant"],
  points=1),

combo(SO, "One gene, two cell types",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> In muscle cells, the gene for enzyme Z is wrapped tightly with histones and is never transcribed.<br><br><b>(나)</b> In liver cells, the gene is transcribed and enzyme Z is made in an inactive form, switched on by phosphorylation when blood sugar drops.",
  [S("In muscle, expression of Z is blocked at the level of DNA accessibility.", True,
     "Tightly packed DNA can't be reached by the transcription machinery, so the gene stays silent."),
   S("In liver, phosphorylation switches Z on without changing its amino acid sequence.", True,
     "Adding a phosphate group is a post-translational modification: the sequence stays the same, but the shape and activity change."),
   S("Muscle and liver cells can carry identical copies of the gene yet differ in whether they make active enzyme Z.", True,
     "All body cells carry the same genes; regulation decides which are expressed, and when.")],
  "Levels of gene regulation · Post-translational modification",
  ["gene_expression_regulation_levels", "post_translational_modification"],
  points=3),

tf(SO, "In a human cell, an mRNA for a cytosolic protein is transcribed, processed, exported and translated.",
  "Ribosomes translate it inside the nucleus, so the protein is finished before the mRNA passes through a nuclear pore.",
  False,
  "Transcription and processing (cap, tail, splicing) happen in the nucleus; the mature mRNA leaves through nuclear pores, and translation happens on ribosomes in the cytosol.",
  "Overview of eukaryotic gene expression · Nuclear pores (Module 3)",
  ["gene_expression_overview_euk", "translation_starts_cytosol", "m3_nuclear_pores_transport"],
  points=1),
]

for _c in CARDS:
    _c["mod"] = MOD
