from cardkit import S, combo, match, tf, mc

MOD = 0
BR = "Connecting Modules 1–6"

CARDS = [
combo(BR, "Is every catalyst a protein?",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Module 6: chemical reactions in cells are catalyzed by proteins called enzymes.<br><br><b>(나)</b> Module 5: the peptidyl transferase center that forms each peptide bond is made of rRNA.",
  [S("(나) shows that at least one biological catalyst is an RNA molecule rather than a protein.", True,
     "The catalytic heart of the ribosome is rRNA, so 'enzymes are proteins' has an important exception (catalytic RNAs are called ribozymes)."),
   S("Like a protein enzyme, the rRNA catalyst speeds peptide bond formation by lowering its activation energy, without changing its ΔG.", True,
     "Every catalyst works by lowering the barrier to the transition state; none changes the free-energy difference between reactants and products."),
   S("Because ribosomes contain RNA, they are membrane-bound organelles of the endomembrane system (Module 1).", False,
     "Ribosomes are RNA–protein complexes with no membrane. They are non-EMS whether free in the cytosol or bound to the ER (Module 1).")],
  "Ribozymes · Catalysts lower activation energy · Ribosomes are non-EMS (Module 1)",
  ["ribosome_rna_protein_subunits", "elongation_steps_peptidyl_transferase", "enzyme_lowers_ea_not_delta_g", "m1_ribosome_non_ems"],
  points=3),

tf(BR, "A 100-amino-acid protein is digested completely into free amino acids in the small intestine.",
  "The digestion uses up 99 water molecules, because each peptide bond is broken by hydrolysis — the reverse of the dehydration that formed it (Module 2).",
  True,
  "100 amino acids are held by 99 peptide bonds. Each was made by releasing one H2O, and each hydrolysis consumes one H2O. Digestion is catabolism: breaking a polymer into its monomers.",
  "Peptide bonds and hydrolysis (Module 2) · Catabolism",
  ["peptide_bond_dehydration", "m2_condensation_hydrolysis", "anabolism_vs_catabolism"],
  points=1),

tf(BR, "Stomach acid has a pH of about 2. At low pH, ionizable groups pick up H+ (Module 2).",
  "At pH 2, a free alanine molecule carries a net positive charge, because its carboxyl group is mostly protonated (–COOH) while its amino group stays –NH3+.",
  True,
  "At physiological pH alanine carries H3N+ and COO- (no net charge). Lowering the pH adds H+ to the carboxylate and removes its negative charge, so mainly the +1 on the amino group remains.",
  "Amino acid charges · pH and ionization (Module 2)",
  ["aa_charged_physiological_ph", "m2_ph_ionization_groups"],
  points=2),

tf(BR, "A folded protein is held together by many hydrogen bonds, ionic bonds and van der Waals contacts, plus a few disulfide bonds.",
  "Because each noncovalent contact is weak, together they contribute little; the disulfide bonds do almost all the work of holding the shape.",
  False,
  "Each weak interaction is far weaker than a covalent bond (Module 2), but a folded protein has hundreds of them, and together they hold the fold. Many proteins have no disulfide bonds at all.",
  "Weak bonds add up (Module 2) · Tertiary interactions",
  ["tertiary_r_group_interactions", "m2_bond_strengths"],
  points=1),

combo(BR, "One gene, two hosts",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> E. coli (Module 1) has no nucleus, and its mRNAs have no 5' cap.<br><br><b>(나)</b> Human mRNAs are capped and processed in the nucleus before export (Module 4).",
  [S("A human gene placed in E. coli needs a Shine-Dalgarno-type sequence upstream of its AUG to be translated efficiently.", True,
     "Bacterial ribosomes find start codons by pairing with Shine-Dalgarno sequences, not caps, so a bacterial ribosome-binding sequence must be supplied."),
   S("An E. coli ribosome must wait until transcription of an mRNA is complete before it can begin translating it.", False,
     "With no nuclear envelope in the way, bacterial ribosomes start on the 5' end of an mRNA while RNA polymerase is still making the rest (Module 4)."),
   S("Antibiotics that block bacterial ribosomes should block human cytosolic ribosomes just as well, since both have A, P and E sites.", False,
     "Both share the same stages and sites, but bacterial ribosomes are smaller and structurally different; many antibiotics exploit those differences and spare human cytosolic ribosomes.")],
  "Translation in prokaryotes vs eukaryotes (Modules 1, 4, 5)",
  ["prok_initiation_shine_dalgarno", "elongation_termination_conserved", "ribosome_rna_protein_subunits", "m1_prok_euk_differences", "m4_coupled_transcription_translation"],
  points=3),

tf(BR, "Viruses carry genes but have no ribosomes and no metabolism of their own (Module 1).",
  "Given only its genome and a supply of free amino acids in a test tube, a virus could make its own proteins.",
  False,
  "Translation needs ribosomes, tRNAs, aminoacyl tRNA synthetases, initiation, elongation and release factors, and an energy supply (ATP) — all provided by a host cell. That's why viruses reproduce only inside cells.",
  "Components of translation · Viruses aren't cells (Module 1)",
  ["translation_components", "cells_need_energy_work", "m1_virus_not_cell"],
  points=1),

tf(BR, "Euglena, a single-celled protist (Module 1), photosynthesizes in the light; kept in the dark, it absorbs organic molecules from the water for both energy and carbon.",
  "Euglena moves between cells A and D of the diagram, depending on the light.",
  True,
  "In light: light energy + carbon from CO2 → A (photoautotroph). In the dark: chemical energy + organic carbon → D (chemoheterotroph). Protists vary in nutrition, and some, like Euglena, switch (Module 1).",
  "Metabolic classes · Protist nutrition (Module 1)",
  ["metabolic_classification_examples", "phototroph_vs_chemotroph", "autotroph_vs_heterotroph", "m1_kingdom_nutrition"],
  points=2, diagram="metabolic_classification_grid"),

tf(BR, "Enzymes called kinases switch many proteins on or off by attaching a phosphate group to the –OH of a serine side chain.",
  "This adds negative charge where a neutral polar side chain used to be, which can change the protein's shape or what it binds.",
  True,
  "A phosphate group is ionized at physiological pH (Module 2), so phosphorylation turns a polar, uncharged side chain into a negatively charged one. New ionic attractions and repulsions can reshape the protein — a post-translational switch.",
  "Post-translational modification · Phosphate groups are charged (Module 2)",
  ["post_translational_modification", "acidic_basic_charged_ionic", "m2_functional_groups"],
  points=1),

tf(BR, "A tRNA is a single RNA strand of 70–90 nucleotides folded into a cloverleaf.",
  "Its cloverleaf is held together by base pairs between two separate RNA strands, as in double-stranded DNA.",
  False,
  "One strand folds back on itself: complementary stretches within the same molecule pair (A–U, G–C) to form the stems, leaving loops such as the anticodon loop.",
  "tRNA structure · Base pairing (Modules 2, 4)",
  ["trna_adapter_structure", "m2_nucleotide_atp_scaffold"],
  points=1),

combo(BR, "What it costs to build a protein",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Each amino acid is attached to its tRNA by a synthetase that spends ATP.<br><br><b>(나)</b> Joining amino acids is a condensation reaction (Module 2).",
  [S("Building a protein is anabolic: it forms new bonds between monomers and needs an energy input.", True,
     "Assembling a polymer from monomers is anabolism, and it is endergonic overall."),
   S("Peptide bond formation is strongly exergonic on its own, which is why making proteins needs no ATP.", False,
     "Joining amino acids by condensation needs energy — it's the reverse of exergonic hydrolysis (Module 2). Cells pay with the ATP spent charging tRNAs."),
   S("Spending ATP to charge tRNAs couples an exergonic reaction to the endergonic job of joining amino acids, making the overall process favourable.", True,
     "Energy from ATP hydrolysis is stored in the bond between the amino acid and its tRNA and released when the peptide bond forms — energetic coupling.")],
  "Anabolism · Energetic coupling · Condensation (Module 2)",
  ["anabolism_vs_catabolism", "energetic_coupling_atp", "aminoacyl_trna_synthetase_charging", "m2_condensation_hydrolysis"],
  points=3),

mc(BR, "The Na+/K+ pump (Module 3) uses about a third of a resting cell's ATP. In Module 6 terms, what is it doing with that energy?",
  "Coupling ATP hydrolysis to pushing ions up their gradients",
  ["Using the kinetic energy of moving ions to make new ATP",
   "Lowering the activation energy of diffusion, the way an enzyme would",
   "Turning all of ATP's energy into ion movement, with no heat lost",
   "Running an exergonic process that needs no energy input"],
  "Moving ions against their gradients is endergonic (it builds potential energy); ATP hydrolysis is exergonic. The pump couples the two so the net ΔG is negative. Some energy is always lost as heat (second law).",
  "Energetic coupling · Active transport (Module 3)",
  ["energetic_coupling_atp", "atp_cellular_work_examples", "m3_active_transport_atp", "second_law_direction_entropy"],
  points=2),

tf(BR, "Histones (Module 4) are made on free ribosomes in the cytosol, but they work in the nucleus.",
  "They reach the nucleus in vesicles budding from the rough ER, like proteins headed for secretion.",
  False,
  "Histones carry an internal signal sequence that directs them into the nucleus through the nuclear pores, which actively transport large proteins (Module 3). The ER and vesicle route serves secreted and endomembrane proteins; it doesn't deliver proteins into the nucleus.",
  "Internal signal → nucleus · Nuclear pores (Module 3)",
  ["sorting_signals_destinations", "translation_starts_cytosol", "m3_nuclear_pores_transport"],
  points=1),

match(BR, "Module 2 chemistry, Module 5–6 jobs",
  "Match each event to the bond or reaction (from Module 2) behind it.",
  "Event", "Bond or reaction",
  [("Joining two amino acids on the ribosome", "A peptide (amide) bond formed by condensation"),
   ("Linking two cysteines in hair keratin", "A disulfide bond between sulfhydryl groups"),
   ("A codon pairing with an anticodon", "Hydrogen bonds between complementary bases"),
   ("ATP + H2O → ADP + Pi", "Hydrolysis of a bond between phosphate groups"),
   ("Holding an α helix in its coil", "Hydrogen bonds between backbone C=O and N–H groups")],
  "The same few bond types do every job: condensation builds peptide bonds; –SH groups join as disulfides; complementary bases hydrogen-bond in nucleic acids; hydrolysis splits ATP's phosphate bonds; and backbone C=O and N–H groups hydrogen-bond in secondary structure.",
  "Bond types (Module 2) across Modules 5–6",
  ["peptide_bond_dehydration", "cysteine_disulfide", "codon_anticodon_antiparallel", "atp_hydrolysis_exergonic_repulsion", "secondary_backbone_hbonds_only", "m2_bond_strengths", "m2_condensation_hydrolysis"],
  points=3),

mc(BR, "In sickle-cell disease, codon 6 of the β-globin gene changes from GAG to GTG on the nontemplate strand. Using the genetic code table, what happens to the protein?",
  "mRNA codon GAG becomes GUG, so Val replaces Glu",
  ["mRNA codon CUC becomes CAC, so His replaces Leu",
   "mRNA codon GAG becomes GTG, which ribosomes can't read",
   "The reading frame shifts, changing every later amino acid",
   "Nothing, since the genetic code is redundant"],
  "The mRNA matches the nontemplate strand with U for T (Module 4): GAG (Glu) → GUG (Val). A single substitution changes one codon and one amino acid without shifting the frame, and it isn't silent, because GUG codes for a different amino acid.",
  "Nontemplate strand → mRNA (Module 4) · Reading the code · Real-world: sickle-cell disease",
  ["codon_triplet_nonoverlapping", "genetic_code_64_redundant", "m4_template_coding_strands"],
  points=2, diagram="genetic_code_table"),

combo(BR, "From frying pan to stomach",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Cooking an egg denatures its proteins (Module 2).<br><br><b>(나)</b> In the stomach, the enzyme pepsin hydrolyzes their peptide bonds, working best near pH 2.",
  [S("Denatured proteins are easier for pepsin to cut, because unfolding exposes peptide bonds that were buried inside the fold.", True,
     "An unfolded chain gives the enzyme's active site access to more of the backbone — one reason cooked protein is easier to digest."),
   S("Pepsin is itself a protein, so in the small intestine it is eventually digested too.", True,
     "Pepsin is inactivated at the intestine's higher pH, and its peptide bonds are hydrolyzed by intestinal protein-digesting enzymes."),
   S("Pepsin speeds digestion by making the ΔG of peptide-bond hydrolysis more negative.", False,
     "Enzymes don't change ΔG; pepsin lowers the activation energy, so a reaction that was already favourable happens fast.")],
  "Denaturation (Module 2) · Enzymes lower activation energy · Digestion",
  ["tertiary_r_group_interactions", "enzymes_are_proteins_active_site", "enzyme_lowers_ea_not_delta_g", "m2_condensation_hydrolysis"],
  points=3),

tf(BR, "During a high fever, body temperature rises from 37°C to about 41°C.",
  "Since molecules move faster at higher temperature, a fever can only speed up the body's enzymes.",
  False,
  "Up to a point, more kinetic energy speeds reactions. But extra heat also disrupts the weak hydrogen bonds and other interactions that hold an enzyme's fold (Module 2); some enzymes start to unfold and lose activity at high temperatures.",
  "Temperature, kinetic energy and protein folding (Modules 2, 5, 6)",
  ["tertiary_r_group_interactions", "enzymes_are_proteins_active_site", "potential_vs_kinetic_energy", "m2_bond_strengths"],
  points=1),

combo(BR, "Supplying the mitochondria",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Mitochondria have their own DNA and bacteria-like ribosomes (Module 3).<br><br><b>(나)</b> Most mitochondrial proteins are nonetheless encoded by genes in the nucleus (Module 5).",
  [S("Nuclear-encoded mitochondrial proteins are made on free ribosomes in the cytosol and carry an amino-terminal signal for import.", True,
     "Proteins for mitochondria and chloroplasts are made in the cytosol and directed by an amino-terminal signal sequence."),
   S("They travel from the rough ER to the mitochondria in vesicles, since mitochondria are part of the endomembrane system.", False,
     "Mitochondria aren't part of the endomembrane system (Module 3) and don't receive vesicles from the ER; their proteins are imported directly."),
   S("A drug that blocks only mitochondrial ribosomes would stop production of proteins encoded by mitochondrial DNA but not of those encoded in the nucleus.", True,
     "Nuclear-encoded proteins are translated by cytosolic ribosomes, which the drug doesn't affect.")],
  "Sorting to mitochondria · Semi-autonomous organelles (Module 3)",
  ["sorting_signals_destinations", "translation_starts_cytosol", "m3_mito_chloro_semi_autonomous"],
  points=3),

tf(BR, "Mature human red blood cells have lost their nucleus and their ribosomes.",
  "They therefore can't replace damaged hemoglobin, since making new protein requires ribosomes to translate mRNA.",
  True,
  "No ribosomes means no translation (and no nucleus means no new mRNA). A red blood cell works with the hemoglobin it was built with and is replaced after about 120 days.",
  "Ribosomes are required for translation · Cell structure and function (Module 1)",
  ["translation_components", "ribosome_rna_protein_subunits", "m1_cell_structure_function"],
  points=1),

combo(BR, "The same push from water",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Phospholipid tails cluster in the interior of the bilayer (Module 3).<br><br><b>(나)</b> Nonpolar side chains cluster in the interior of a folded protein (Module 5).",
  [S("Both clusterings are driven mainly by water molecules hydrogen-bonding with one another and excluding nonpolar groups (Module 2).", True,
     "Water's network of hydrogen bonds pushes nonpolar groups together; the attraction between the nonpolar groups themselves is weak."),
   S("Both are held together by covalent bonds between neighbouring nonpolar groups.", False,
     "No covalent bonds join the tails or the clustered side chains; the clusters can rearrange, which is why membranes are fluid."),
   S("The membrane-spanning segment of an integral membrane protein has mostly charged side chains facing the lipid tails.", False,
     "Side chains facing the lipid tails are mostly nonpolar; charged groups there would sit in a nonpolar environment (Module 3).")],
  "Hydrophobic effect (Module 2) · Bilayers (Module 3) · Protein folding (Module 5)",
  ["hydrophobic_aa_buried_vdw", "m2_hydrophobic_effect_water", "m3_membrane_protein_types"],
  points=3),

tf(BR, "RNA polymerase adds each nucleotide using energy from the incoming nucleoside triphosphate, releasing pyrophosphate (Module 4).",
  "This is energetic coupling: splitting off pyrophosphate is exergonic and drives the endergonic formation of a phosphodiester bond.",
  True,
  "Forming a phosphodiester bond by condensation needs energy; breaking the phosphate–phosphate bond of the incoming triphosphate releases it. The two steps are linked, so the net ΔG is negative — the same strategy ATP-driven reactions use.",
  "Energetic coupling · Nucleotide polymerization (Module 4)",
  ["energetic_coupling_atp", "atp_phosphate_bonds_energy", "m4_ntp_energy_polymerization", "m2_condensation_hydrolysis"],
  points=2),

tf(BR, "When water vapour condenses into liquid, hydrogen bonds form between water molecules (Module 2).",
  "Forming these bonds requires an input of energy, so condensation absorbs heat from the surroundings.",
  False,
  "Forming bonds releases energy; breaking them requires it. Condensing vapour releases heat (which is why steam burns are so severe), just as forming stronger bonds in a reaction's products releases energy.",
  "Bond formation releases energy · Hydrogen bonds in water (Module 2)",
  ["chemical_energy_bond_strength", "m2_bond_strengths"],
  points=1),

mc(BR, "Two patients have deletions inside the coding region of the dystrophin gene. Patient A loses 6 nucleotides and has mild muscle weakness (Becker muscular dystrophy); patient B loses 5 nucleotides and has severe disease (Duchenne). Which explanation fits best?",
  "A's deletion removes two whole codons, keeping the frame; B's shifts the frame downstream",
  ["B's deletion removes more amino acids than A's, so B's protein is shorter but still in frame",
   "Deleting 6 nucleotides changes the start codon, while deleting 5 nucleotides leaves it intact",
   "A's deletion is silent because the genetic code is redundant, but B's deletion is not silent",
   "Deleting 5 nucleotides destroys the mRNA's 5' cap, so no ribosome can start translating it at all"],
  "A DNA deletion is copied into the mRNA (Module 4). Six nucleotides are two whole codons, so the frame is kept and the protein just lacks two amino acids. Five is not a multiple of three: every codon after the deletion is misread, and a premature stop codon soon ends the chain, usually leaving a nonfunctional protein.",
  "Reading frame · Nonoverlapping triplets · Central dogma (Module 4) · Real-world: muscular dystrophy",
  ["reading_frame", "codon_triplet_nonoverlapping", "start_stop_codons", "m4_central_dogma_flow"],
  points=2),

combo(BR, "An antibiotic that garbles proteins",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Streptomycin binds the small subunit of bacterial ribosomes and makes them misread codons.<br><br><b>(나)</b> In bacteria, genes are transcribed by RNA polymerase and translated by ribosomes (Module 4).",
  [S("Misreading puts wrong amino acids at scattered positions, producing many misfolded, nonfunctional proteins.", True,
     "A wrong codon–anticodon match inserts the wrong amino acid; changed primary structure can derail folding across the cell's proteins."),
   S("Streptomycin works by blocking transcription, so bacterial mRNAs are never made.", False,
     "It acts on ribosomes (translation); transcription by RNA polymerase continues."),
   S("Because codons are read in triplets, each misreading shifts the reading frame for the rest of the protein.", False,
     "Misreading a codon substitutes one amino acid; the ribosome still moves three bases at a time, so the frame is kept.")],
  "Ribosome accuracy · Reading frame · Transcription vs translation (Module 4)",
  ["codon_anticodon_antiparallel", "reading_frame", "sequence_determines_folding", "m4_central_dogma_flow"],
  points=3),

tf(BR, "In a polypeptide backbone, the O of each C=O and the N of each N–H are more electronegative than the atoms they're bonded to (Module 2).",
  "This polarity is what allows a C=O of one residue and an N–H of another to form the hydrogen bonds of helices and sheets.",
  True,
  "Electronegative O and N pull electrons toward themselves, giving the O a partial negative charge and the H on N a partial positive charge — the ingredients of a hydrogen bond (Module 2). Secondary structure is built from these backbone H-bonds.",
  "Electronegativity and H-bonds (Module 2) · Secondary structure",
  ["secondary_backbone_hbonds_only", "m2_electronegativity_polarity"],
  points=1),

match(BR, "Where in the cell?",
  "Match each event to where it happens in a human cell.",
  "Event", "Location",
  [("Adding a 5' cap to a primary transcript", "Nucleus"),
   ("Charging tRNAs with their amino acids", "Cytosol"),
   ("Translating an mRNA for insulin once SRP has docked", "Ribosomes on the rough ER"),
   ("Cutting off the signal sequence of a secreted protein", "ER lumen side of the ER membrane"),
   ("Making the proteins encoded by mitochondrial DNA", "Mitochondrial matrix")],
  "RNA processing happens in the nucleus; tRNA charging and the start of all translation happen in the cytosol; SRP moves a secretory protein's translation to the rough ER, where the signal sequence is removed on the lumen side; mitochondria translate their own few genes on their own ribosomes in the matrix (Module 3).",
  "Where each step of gene expression happens (Modules 1, 3, 4, 5)",
  ["translation_starts_cytosol", "srp_er_targeting", "gene_expression_overview_euk", "m3_mito_chloro_semi_autonomous", "m4_mrna_processing_cap_tail_splicing"],
  points=3),

tf(BR, "Module 1 lists acquiring and using energy as a property of every cell, including plant cells.",
  "Even a photoautotroph's cells need ATP, because light cannot directly power processes such as protein synthesis.",
  True,
  "Light energy is first captured as chemical energy (ATP and sugars). ATP is the currency that actually drives cellular work everywhere in the plant, including root cells that never see light.",
  "ATP as universal currency · Cells acquire and use energy (Module 1)",
  ["cells_need_energy_work", "atp_energy_currency", "m1_cell_property_energy"],
  points=1),

mc(BR, "Why must a cell keep spending ATP to maintain its Na+ gradient, even when nothing else changes?",
  "Na+ leaks back down its gradient, so the pump must keep restoring it",
  ["The pump uses up Na+ ions, so the cell must keep making new ones to pump",
   "ATP keeps the bilayer fluid, and the gradient depends on fluidity",
   "The gradient stores no energy, so it has to be paid for again",
   "The pump works only while an enzyme lowers its ΔG below zero"],
  "A gradient is an ordered, high-energy state, and spontaneous change runs toward lower energy and higher entropy (second law): ions leak back through channels. Keeping the gradient means continually paying with ATP hydrolysis (Module 3).",
  "Second law · Gradients store potential energy (Module 3)",
  ["second_law_direction_entropy", "potential_vs_kinetic_energy", "m3_active_transport_atp"],
  points=2),
]

for _c in CARDS:
    _c["mod"] = MOD
