from cardkit import S, combo, match, tf, mc

MOD = 5
AA = "Amino Acids & Peptide Bonds"
PS = "Levels of Protein Structure"

CARDS = [
# ───────────────────────── Amino Acids & Peptide Bonds ─────────────────────────
combo(AA, "Reading eight side chains",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> All eight amino acids are drawn as they exist at physiological pH (about 7.4).<br><br><b>(나)</b> Panels A–G share the same backbone; only the side chain below the α carbon differs.",
  [S("The side chains in panels C and D carry opposite full charges, so they can form an ionic bond if folding brings them together.", True,
     "C's –COO- is negative (acidic) and D's –NH3+ is positive (basic); opposite charges attract."),
   S("The side chain in panel B can hydrogen-bond with water through its –OH, even though it carries no full charge.", True,
     "Oxygen is electronegative, so the –OH is polar: B is a polar, uncharged, hydrophilic side chain."),
   S("In a folded water-soluble protein, the side chain in panel G would most likely be found buried in the interior.", True,
     "A CH2 plus a benzene ring is all carbon and hydrogen — nonpolar and hydrophobic — so it clusters away from water inside the fold.")],
  "R-group classes · Ionic bonds between side chains · Polarity from electronegativity (Module 2)",
  ["r_group_classification_criteria", "acidic_basic_charged_ionic", "hydrophilic_aa_hbond_surface", "hydrophobic_aa_buried_vdw", "m2_electronegativity_polarity"],
  points=3, diagram="r_group_gallery"),

match(AA, "Which side chain fits?",
  "Using the diagram, match each description to the side chain that fits it.",
  "Description", "Side chain",
  [("Gives the backbone the most freedom to rotate and bend", "Panel F: –H"),
   ("Restricts rotation of the backbone, limiting folding around it", "Panel H: ring bonded back to the nitrogen"),
   ("Can form a covalent cross-bridge with another copy of itself", "Panel E: –CH2–SH"),
   ("Positively charged at physiological pH", "Panel D: –(CH2)4–NH3+"),
   ("Polar but uncharged; hydrogen-bonds with water", "Panel B: –CH2–OH")],
  "Panel F is glycine (side chain H): tiny, so the C–N bond rotates freely. H is proline: its side chain loops back to the amino nitrogen and locks rotation. E is cysteine: two –SH groups can join as an S–S disulfide bridge. D is lysine (basic, +). B is serine: its –OH is polar but uncharged.",
  "Special amino acids: glycine, proline, cysteine · Charged vs polar side chains",
  ["glycine_flexibility", "proline_rigidity", "cysteine_disulfide", "acidic_basic_charged_ionic", "hydrophilic_aa_hbond_surface"],
  points=3, diagram="r_group_gallery"),

tf(AA, "A protein designer wants to make a floppy loop on a protein's surface more rigid. One of the loop's amino acids is the one in panel F of the diagram.",
  "Replacing it with the amino acid in panel H would stiffen the loop more than the amino acid in panel D would, even though D's side chain is much longer.",
  True,
  "Rigidity doesn't come from size. D's long chain (lysine) points away from the backbone and has freely rotating bonds of its own, while H's side chain (proline) is bonded to the backbone nitrogen itself, which locks rotation about the C–N bond.",
  "Proline restricts rotation · Side chain properties, not size · Real-world: protein design",
  ["proline_rigidity", "r_group_determines_properties"],
  points=2, diagram="r_group_gallery"),

mc(AA, "A protein engineer replaces a glycine in a tight hairpin turn with alanine (side chain –CH3). The protein no longer folds correctly. Which explanation fits best?",
  "Alanine's –CH3 limits backbone rotation, so the chain can't bend as sharply",
  ["Alanine's –CH3 hydrogen-bonds to the backbone, pinning the turn open",
   "Alanine's side chain bonds back to its own backbone nitrogen, closing a ring",
   "Alanine lacks the H that glycine's side chain uses to hydrogen-bond across the turn",
   "Alanine's –CH3 is nonpolar, so the turn is pulled into the protein's interior"],
  "Glycine's side chain is just H, so the backbone can rotate freely about the C–N bond — the flexibility a tight turn needs. Even a small –CH3 restricts that rotation. Neither glycine's H nor alanine's –CH3 can hydrogen-bond (both are bonded to carbon), alanine has no ring (that's proline), and one small nonpolar group doesn't drag a whole turn into the core.",
  "Glycine flexibility · Sequence determines folding",
  ["glycine_flexibility", "sequence_determines_folding", "r_group_determines_properties"],
  points=2),

tf(AA, "Collagen, the main protein of bone and tendon, is a tight triple helix. Every third amino acid is glycine, and each glycine sits at the crowded centre where the three chains meet.",
  "A mutation replacing one of these glycines with a bulkier amino acid can weaken collagen, because only glycine's single H atom fits in that central position.",
  True,
  "Glycine has the smallest side chain (H). A larger side chain can't pack into the helix centre and distorts the triple helix — the cause of many cases of osteogenesis imperfecta (brittle bone disease).",
  "Glycine: the smallest side chain · Real-world: brittle bone disease",
  ["glycine_flexibility", "r_group_determines_properties", "sequence_determines_folding"],
  points=2),

tf(AA, "A perm breaks the disulfide bonds in hair keratin with a reducing agent, holds the hair around curlers, then re-forms disulfide bonds with an oxidizing agent.",
  "The curl lasts because the disulfide bonds re-form between exactly the same pairs of cysteines as before.",
  False,
  "While the hair is held in its new shape, cysteines that weren't partners before sit side by side, and the oxidizer links them into new S–S bridges. Covalent bridges in new positions hold the new shape; re-forming the old pairs would simply restore the original shape.",
  "Disulfide cross-bridges · Real-world: perms",
  ["cysteine_disulfide", "tertiary_r_group_interactions"],
  points=2),

mc(AA, "The peptide Val–Gly–Ala–His–Lys is assembled from free amino acids by condensation reactions. How many water molecules are released, and which amino acid carries the free amino group?",
  "4 water molecules; Val",
  ["5 water molecules; Val",
   "4 water molecules; Lys",
   "5 water molecules; Lys",
   "3 water molecules; Val"],
  "Five amino acids are joined by 4 peptide bonds, and each dehydration releases one H2O. Sequences are written from the amino (N) end to the carboxyl (C) end, so Val, written first, keeps the free amino group, and Lys keeps the free carboxyl group.",
  "Peptide bonds form by dehydration · N- and C-terminus · Writing sequences N→C",
  ["peptide_bond_dehydration", "n_terminus_c_terminus", "primary_structure_sequence_n_to_c", "m2_condensation_hydrolysis"],
  points=2),

tf(AA, "One lab reports a tripeptide as K-G-V. Another lab reports a tripeptide as V-G-K.",
  "These are the same molecule: both contain lysine, glycine and valine, just written from opposite ends.",
  False,
  "Sequences are written from the N-terminus to the C-terminus. K-G-V has lysine at the free amino end; V-G-K has valine there and lysine at the carboxyl end. A backbone has direction (amino end ≠ carboxyl end), so these are different peptides.",
  "Primary structure is written N→C · Polypeptides have direction",
  ["n_terminus_c_terminus", "primary_structure_sequence_n_to_c"],
  points=1),

mc(AA, "Using the diagram, a side chain on a protein's surface that forms an ionic bond with a nearby –COO- changes from the one in panel D to the one in panel C. What is the main change at that spot?",
  "The attraction becomes a repulsion, since both groups are now negative",
  ["It becomes nonpolar and tends to move into the folded protein's interior",
   "It gains the ability to form a disulfide bridge with another copy",
   "Nothing changes, since both side chains are charged and hydrophilic",
   "The ionic bond gets stronger, since C's group carries the larger charge"],
  "D (–(CH2)4–NH3+, lysine) is basic and positive, so it attracts the nearby –COO-; C (–CH2–COO-, aspartate) is acidic and negative, so the two groups now repel and the ionic bond is lost. Both side chains are charged and hydrophilic, so the spot stays at the surface; neither has an –SH, and each carries a single charge.",
  "Acidic vs basic side chains · Ionic bonds need opposite charges",
  ["acidic_basic_charged_ionic", "r_group_classification_criteria"],
  points=1, diagram="r_group_gallery"),

tf(AA, "A protein drug clumps together in its storage vial. Its designers find two valines (side chain –CH(CH3)2) exposed on its surface and replace them with lysines (side chain –(CH2)4–NH3+).",
  "The swap should make the clumping worse, because the new charged side chains will stick to nonpolar patches on neighbouring drug molecules.",
  False,
  "The reverse: exposed nonpolar side chains are what make the molecules stick, since water pushes nonpolar groups together. Charged lysines interact with water (and repel each other), so the swap makes the surface more hydrophilic and the drug clumps less.",
  "Hydrophobic vs charged side chains · Real-world: protein drug formulation",
  ["hydrophobic_aa_buried_vdw", "r_group_determines_properties", "m2_hydrophobic_effect_water"],
  points=2),

tf(AA, "Proteins are built from 20 kinds of amino acids, like words built from an alphabet.",
  "A chain only 3 amino acids long already has 8,000 possible sequences.",
  True,
  "Each of the 3 positions can hold any of 20 amino acids: 20 × 20 × 20 = 8,000. For a 300-amino-acid protein the number is 20^300 — one reason proteins can be so diverse and versatile.",
  "20 amino acids as an alphabet · Protein diversity",
  ["proteins_diverse_versatile", "primary_structure_sequence_n_to_c"],
  points=1),

combo(AA, "One backbone, twenty personalities",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Every amino acid has an amino group, a carboxyl group and an H bonded to its α carbon; only the fourth group, the R group, differs.<br><br><b>(나)</b> At physiological pH, a free amino acid carries H3N+ and COO-.",
  [S("Two different proteins of the same length share the same repeating backbone (N–C–C–N–C–C…); they differ only in the side chains attached to it.", True,
     "Peptide bonds always join the same backbone atoms, so sequence differences show up only in the R groups sticking out from the chain."),
   S("Because of (나), every amino acid in a folded protein carries both an H3N+ and a COO- on its backbone.", False,
     "Inside a chain, the amino and carboxyl groups are used up in peptide bonds. Only the first amino acid keeps a free amino group (N-terminus) and only the last keeps a free carboxyl group (C-terminus)."),
   S("Proline is the only amino acid whose α carbon carries two identical groups.", False,
     "That's glycine, whose R group is a second H — so its α carbon isn't asymmetric. Proline's α carbon carries four different groups; its side chain loops back to the nitrogen.")],
  "Amino acid structure · Charged ends at physiological pH · N- and C-terminus",
  ["aa_four_groups_alpha_carbon", "aa_charged_physiological_ph", "n_terminus_c_terminus", "glycine_flexibility"],
  points=3),

mc(AA, "Using the diagram, which pair of side chains, brought together by folding, could join two parts of a protein with a covalent bond?",
  "E and E (two –CH2–SH groups)",
  ["C and D (–COO- and –NH3+)",
   "B and B (two –CH2–OH groups)",
   "A and G (–CH3 and the ring)",
   "F and F (two –H atoms)"],
  "Two cysteine –SH groups can be joined into an S–S disulfide bond — a covalent cross-bridge, far stronger than the ionic bond C and D can form, the hydrogen bonds between B's –OH groups, or the weak van der Waals contacts between nonpolar A and G.",
  "Disulfide bonds are covalent · Bond strengths (Module 2)",
  ["cysteine_disulfide", "tertiary_r_group_interactions", "m2_bond_strengths"],
  points=1, diagram="r_group_gallery"),

tf(AA, "Proteins are built from only 20 kinds of amino acids, yet they do thousands of different jobs. Two proteins turn out to contain exactly the same number of each kind of amino acid.",
  "So they will fold into the same shape and do the same job.",
  False,
  "What matters is the order of the amino acids, not just which ones are present: the sequence of side chains decides how the chain folds, and the shape decides the job. The same amino acids in a different order make a different protein, just as the same letters can spell different words.",
  "Proteins are diverse and versatile · Sequence → shape → function",
  ["proteins_diverse_versatile", "sequence_determines_folding", "primary_structure_sequence_n_to_c"],
  points=1),

# ───────────────────────── Levels of Protein Structure ─────────────────────────
combo(PS, "Two backbone patterns",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> In each structure, one dashed line is labelled with the two groups it joins.<br><br><b>(나)</b> Each R marks a side chain sticking out from the backbone.",
  [S("Every dashed bond links a backbone C=O to a backbone N–H; none involves an R group.", True,
     "Secondary structure comes from hydrogen bonds between backbone groups of nearby amino acids; side chains aren't part of these bonds."),
   S("If the helix continued past residue 11, the N–H of residue 12 would bond to the C=O of residue 8.", True,
     "Each C=O bonds to the N–H four residues along (1–5, 2–6, 3–7…), so residue 12's N–H pairs with residue 8's C=O, tying each turn of the helix to the next."),
   S("The sheet's two strands are parallel, since they lie side by side.", False,
     "Side by side doesn't mean the same direction: the top strand runs N→C left to right and the bottom strand right to left, so they're antiparallel. Sheets can be either.")],
  "Secondary structure: backbone H-bonds only · α helix · β sheet",
  ["secondary_backbone_hbonds_only", "alpha_helix_i_plus_4", "beta_sheet_parallel_antiparallel"],
  points=3, diagram="backbone_hbond_patterns"),

tf(PS, "An isolated 11-residue segment folds into the helix in the diagram, with residue 1 at its N-terminus.",
  "Residues 8–11 have their N–H groups hydrogen-bonded within the segment, but their C=O groups have no partner.",
  True,
  "Each C=O of residue n pairs with the N–H of residue n + 4. Residues 8–11 would need partners 12–15, which don't exist, while their own N–H groups receive bonds from residues 4–7. At the other end, residues 1–4 have unpaired N–H groups.",
  "α helix: residue n bonds to n + 4",
  ["alpha_helix_i_plus_4", "secondary_backbone_hbonds_only"],
  points=2, diagram="backbone_hbond_patterns"),

mc(PS, "Proline's side chain bonds to its own backbone nitrogen, so in a chain that nitrogen carries no H. If residue 7 of the helix in the diagram were proline, which of the helix's hydrogen bonds would be lost?",
  "The one between residue 3's C=O and residue 7's N–H",
  ["The one between residue 7's C=O and residue 11's N–H",
   "The one between residue 6's C=O and residue 10's N–H",
   "The one between residue 4's C=O and residue 8's N–H",
   "None, since helix H-bonds involve only backbone atoms"],
  "Residue 7's N–H is the partner of residue 3's C=O (n to n + 4). Proline has no N–H to give, so that bond is lost, while its C=O can still bond to residue 11's N–H. Here a side chain matters after all: proline's ring changes a backbone atom itself, one reason proline disrupts helices.",
  "α helix pattern · Proline restricts the backbone",
  ["alpha_helix_i_plus_4", "secondary_backbone_hbonds_only"],
  points=2, diagram="backbone_hbond_patterns"),

combo(PS, "What holds the fold together?",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> One sample is treated with a reducing agent that turns each –S–S– back into two –SH groups.<br><br><b>(나)</b> A second sample is moved from pH 7 into strong acid (pH 1).",
  [S("(가) breaks contact A but leaves the protein's primary structure unchanged.", True,
     "A disulfide bridge links two side chains; it isn't part of the backbone, so the amino acid sequence (held by peptide bonds) is untouched."),
   S("In (나), contact B gets stronger, because the extra H+ adds positive charge to both of its groups.", False,
     "COO- picks up H+ and becomes uncharged COOH, so the attraction between opposite charges at B is lost, not strengthened."),
   S("In (나), contact D is lost, because its nonpolar groups pick up H+ and become charged.", False,
     "Nonpolar groups such as –CH3 can't gain or lose H+, so acid doesn't act on D directly; pH acts on ionizable groups like those at B.")],
  "Tertiary interactions · Disulfide vs ionic bonds · pH and ionization (Module 2)",
  ["tertiary_r_group_interactions", "cysteine_disulfide", "acidic_basic_charged_ionic", "m2_ph_ionization_groups"],
  points=3, diagram="tertiary_interactions_map"),

match(PS, "Four ways to unfold a protein",
  "Using the diagram, match each treatment to the contact it most directly disrupts.",
  "Treatment", "Contact",
  [("A reducing agent that adds H to each sulfur", "A: CH2–S–S–CH2"),
   ("Concentrated salt, whose ions crowd around charged groups", "B: COO- facing H3N+"),
   ("Urea, which hydrogen-bonds to polar groups in place of their partners", "C: OH facing O=C"),
   ("A detergent whose nonpolar tails coat nonpolar groups", "D: the clustered nonpolar groups")],
  "Each treatment targets one interaction type: reducing agents split covalent disulfides (A); ions shield the charges of an ionic bond (B); urea competes for hydrogen bonds (C); detergents surround nonpolar groups so they no longer need to hide from water (D).",
  "Tertiary interactions · Bond types (Module 2) · Denaturation",
  ["tertiary_r_group_interactions", "cysteine_disulfide", "acidic_basic_charged_ionic", "hydrophilic_aa_hbond_surface", "hydrophobic_aa_buried_vdw", "m2_bond_strengths"],
  points=3, diagram="tertiary_interactions_map"),

tf(PS, "In the diagram, contact D sits in the middle of the fold, surrounded by the chain, while water lies outside.",
  "D holds together mainly because nonpolar groups attract one another strongly, much as the opposite charges at B do.",
  False,
  "Nonpolar groups attract one another only weakly (van der Waals forces). They cluster mainly because water molecules hydrogen-bond with each other and push nonpolar groups aside (Module 2), so the groups end up hidden in the interior.",
  "Hydrophobic interior · Water drives nonpolar clustering (Module 2)",
  ["hydrophobic_aa_buried_vdw", "m2_hydrophobic_effect_water", "m2_bond_strengths"],
  points=2, diagram="tertiary_interactions_map"),

mc(PS, "An enzyme is a homodimer: two identical chains held together by side-chain contacts. A mutation changes one amino acid on the surface where the two chains touch. Which outcome is most likely?",
  "Each chain can still fold, but the pair no longer assembles into the enzyme",
  ["Nothing changes, since surface amino acids don't affect quaternary structure",
   "The two chains now differ in sequence, so the enzyme becomes a heterodimer",
   "The peptide bonds that join the two chains to each other are broken",
   "The chains form a disulfide bridge at that spot, locking them together"],
  "Subunits are held together by the same side-chain interactions as tertiary structure, so a changed contact residue can block pairing. Both chains come from the same mutated gene, so they're still identical (still a homodimer), and subunits aren't joined by peptide bonds.",
  "Quaternary structure · Homodimer vs heterodimer",
  ["quaternary_subunits_homo_hetero", "sequence_determines_folding", "four_levels_conformation"],
  points=2),

tf(PS, "Insulin's A and B chains are cut from one longer precursor polypeptide after it has folded. In the folded precursor, two cysteines in the A segment are disulfide-bonded to two cysteines in the B segment.",
  "Once the connecting segment is cut out, only weak noncovalent interactions hold the A and B chains together.",
  False,
  "Cutting out the connecting segment breaks peptide bonds, not disulfides. The two disulfide bonds, each joining a cysteine on chain A to a cysteine on chain B, are covalent and still hold the chains together.",
  "Disulfide bridges between chains · Post-translational cleavage",
  ["cysteine_disulfide"],
  points=1),

mc(PS, "An enzyme is unfolded with chemicals that break its hydrogen bonds and disulfide bonds, leaving its peptide bonds intact. When the chemicals are slowly removed, the chain refolds into its active shape. What does this show?",
  "The amino acid sequence alone holds the information for the folded shape",
  ["The peptide bonds alone hold the folded shape, since they were never broken",
   "The chain refolded at random and happened to find the active shape",
   "Refolding needed a correctly folded copy of the enzyme as a template",
   "Secondary and tertiary structure don't depend on the sequence"],
  "Only the sequence (primary structure) survived, yet the same active shape came back, so the sequence holds the information for secondary and tertiary structure. The peptide bonds just link the chain; the shape itself is held by the interactions that re-formed: hydrogen bonds, ionic bonds, hydrophobic interactions and disulfides.",
  "Primary structure determines higher levels · Denaturation and refolding",
  ["primary_structure_sequence_n_to_c", "sequence_determines_folding"],
  points=2),

tf(PS, "A peptide alternates nonpolar valine with charged lysine or glutamate: Val–Lys–Val–Glu–Val–Lys–Val–Glu.",
  "If the peptide is stretched out as a strand, replacing the valine at position 3 with lysine would put a charged side chain on the strand's nonpolar face.",
  True,
  "R groups alternate sides along an extended chain, so positions 1, 3, 5 and 7 (all Val) share one face and positions 2, 4, 6 and 8 (Lys, Glu) the other. A lysine at position 3 would sit among the valines, on the nonpolar face that would otherwise pack against the protein's interior.",
  "R groups alternate sides · Nonpolar and charged faces",
  ["r_groups_alternate_sides"],
  points=2),

tf(PS, "In the diagram's sheet, a third strand is added below the bottom strand, running from N at the left to C at the right.",
  "The new strand is antiparallel to the bottom strand and parallel to the top strand.",
  True,
  "The bottom strand runs N→C right to left and the top strand left to right. A strand running left to right is opposite to the bottom strand (antiparallel) and matches the top one (parallel). Both arrangements occur in sheets.",
  "β sheets: parallel and antiparallel strands",
  ["beta_sheet_parallel_antiparallel"],
  points=1, diagram="backbone_hbond_patterns"),

mc(PS, "In the diagram's sheet, R groups alternate between above the sheet (filled) and below it (hollow). The sheet lies against the protein's nonpolar interior on one face, with water on the other. Which pattern along each strand fits best?",
  "Nonpolar and polar side chains alternating along the strand",
  ["Nonpolar side chains at every position along the strand",
   "Charged side chains at every position along the strand",
   "Nonpolar side chains on one strand, polar side chains on the other",
   "Glycine at every position so that the sheet can bend"],
  "Consecutive residues point to opposite faces, so alternating nonpolar and polar residues put every nonpolar side chain on the interior face and every polar one on the water face. An all-nonpolar strand would leave half its side chains facing water.",
  "R groups alternate sides · Faces of a β sheet",
  ["r_groups_alternate_sides", "hydrophobic_aa_buried_vdw", "hydrophilic_aa_hbond_surface"],
  points=2, diagram="backbone_hbond_patterns"),

match(PS, "Which level of structure?",
  "Match each observation to the level of protein structure it describes.",
  "Observation", "Level",
  [("A mutation swaps the 6th amino acid of the chain for a different one", "Primary"),
   ("In a stretch of keratin, each C=O bonds to the N–H four amino acids along", "Secondary"),
   ("A disulfide bond links cysteine 30 to cysteine 115 of the same chain", "Tertiary"),
   ("An enzyme works only after its α chain and β chain pair up", "Quaternary")],
  "Primary = the sequence; secondary = local backbone H-bond patterns (here, the α helix's n to n + 4 bonds); tertiary = the whole folded shape of one chain, held by bonds between side chains far apart in the sequence; quaternary = how separate chains (subunits) assemble.",
  "Four levels of protein structure",
  ["four_levels_conformation", "primary_structure_sequence_n_to_c", "secondary_backbone_hbonds_only", "tertiary_r_group_interactions", "quaternary_subunits_homo_hetero"],
  points=3),
]

for _c in CARDS:
    _c["mod"] = MOD
