from cardkit import S, combo, match, tf, mc

MOD = 6
EM = "Energy & Metabolism"
AT = "ATP & Energetic Coupling"
TH = "Thermodynamics & Free Energy"
EN = "Enzymes & Their Regulation"

CARDS = [
# ───────────────────────── Energy & Metabolism ─────────────────────────
combo(EM, "Who goes where?",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> Cyanobacteria use light energy to build sugars from CO2.<br><br><b>(나)</b> Sulfur-oxidizing bacteria get energy by oxidizing hydrogen sulfide (H2S) and build sugars from CO2.",
  [S("Cyanobacteria belong in cell A and sulfur-oxidizing bacteria in cell B.", True,
     "Both take their carbon from CO2 (top row); cyanobacteria get energy from light (A), sulfur bacteria from a chemical compound (B)."),
   S("Both are phototrophs, since both make sugar from CO2.", False,
     "Making sugar from CO2 makes them both autotrophs. 'Phototroph' describes the energy source, and only the cyanobacteria use light."),
   S("A human belongs in cell C, since humans get their carbon from organic molecules.", False,
     "Humans do get carbon from organic molecules, but their energy comes from chemical compounds in food, not light — cell D.")],
  "Phototroph vs chemotroph · Autotroph vs heterotroph",
  ["phototroph_vs_chemotroph", "autotroph_vs_heterotroph", "metabolic_classification_examples"],
  points=3, diagram="metabolic_classification_grid"),

tf(EM, "Heliobacteria use light to make ATP but cannot fix CO2; they absorb organic molecules such as pyruvate as their carbon source.",
  "Heliobacteria belong in cell C of the diagram.",
  True,
  "Energy from light puts them in the left column; carbon from organic molecules puts them in the bottom row: cell C, the photoheterotrophs.",
  "Photoheterotrophs",
  ["metabolic_classification_examples", "phototroph_vs_chemotroph", "autotroph_vs_heterotroph"],
  points=1, diagram="metabolic_classification_grid"),

mc(EM, "Using the diagram, a deep-sea vent bacterium builds all its organic molecules from CO2 and gets its energy by oxidizing hydrogen gas (H2). A fungus rotting a log gets both its energy and its carbon from the wood. Which cells do they belong in?",
  "The bacterium in B; the fungus in D",
  ["The bacterium in A; the fungus in D",
   "The bacterium in B; the fungus in C",
   "Both in D, since neither uses light",
   "The bacterium in D; the fungus in B"],
  "The vent bacterium: chemical energy + carbon from CO2 → B (a chemoautotroph, like the notes' hydrogen bacteria). The fungus: chemical energy + organic carbon → D (a chemoheterotroph); fungi are heterotrophs (Module 1).",
  "Chemoautotrophs vs chemoheterotrophs · Fungi are heterotrophs (Module 1)",
  ["metabolic_classification_examples", "autotroph_vs_heterotroph", "phototroph_vs_chemotroph", "m1_kingdom_nutrition"],
  points=2, diagram="metabolic_classification_grid"),

match(EM, "Where is the energy?",
  "Match each example to the form of energy it best shows.",
  "Example", "Form of energy",
  [("Water held behind a dam", "Potential energy of position"),
   ("The bonds of a glucose molecule", "Chemical energy stored in bonds"),
   ("A sperm cell's beating flagellum", "Kinetic energy: movement of a whole structure"),
   ("Heat given off by a working muscle", "Kinetic energy: random motion of molecules"),
   ("A high concentration of Na+ outside a cell", "Potential energy stored in a gradient")],
  "Potential energy is stored — by position, in bonds, or in a concentration difference; kinetic energy is motion, whether of a whole flagellum or of molecules jiggling as heat. One form converts into another: the dam's water spins a turbine, and the Na+ gradient powers transport (Module 3).",
  "Potential vs kinetic energy · Chemical energy · Gradients (Module 3)",
  ["potential_vs_kinetic_energy", "chemical_energy_bond_strength", "m3_active_transport_atp"],
  points=3),

tf(EM, "The notes link bond strength to potential energy: strong bonds hold less potential energy and weak bonds hold more.",
  "So a reaction that replaces weaker bonds with stronger ones ends with products of lower potential energy, releasing energy.",
  True,
  "Stronger bonds store less potential energy. If the products are held by stronger bonds than the reactants, the difference is released — the hallmark of an exergonic reaction.",
  "Bond strength and potential energy · Exergonic reactions",
  ["chemical_energy_bond_strength", "exergonic_vs_endergonic"],
  points=2),

mc(EM, "Using the diagram, a mutation inactivates enzyme e2. Which molecule builds up first, and what can happen to it?",
  "B builds up, and more of it may flow to E and F",
  ["C builds up, since it can no longer be converted into D",
   "A builds up, since B can no longer be made from it",
   "D builds up, since nothing downstream uses it",
   "Nothing builds up, since each enzyme works independently"],
  "In a pathway, each product is the next step's reactant. With e2 gone, B can't become C, so B accumulates (and C and D run low); e4 can still use B, so the excess may flow toward E and F. Inherited diseases such as PKU work this way: a missing enzyme makes its substrate pile up and be diverted into side products.",
  "Metabolic pathways · Real-world: inherited enzyme defects",
  ["metabolism_definition_pathways", "enzyme_catalysis_anabolic_catabolic"],
  points=2, diagram="branched_pathway"),

tf(EM, "The human brain is about 2% of body mass but uses about 20% of the body's energy at rest. Its neurons don't crawl, contract or divide.",
  "Since its neurons don't move, little of that energy can be going into cellular work; most must be lost directly as heat.",
  False,
  "Cellular work isn't only movement: it includes pumping ions across membranes, making molecules such as proteins, and moving vesicles. Neurons spend much of their ATP on Na+/K+ pumps that restore the ion gradients they use to signal (Module 3).",
  "Kinds of cellular work · ATP-driven pumps (Module 3) · Real-world: the brain's energy use",
  ["cells_need_energy_work", "atp_cellular_work_examples", "m3_active_transport_atp"],
  points=1),

combo(EM, "Build it up, break it down",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> After a meal, liver cells link glucose molecules into glycogen.<br><br><b>(나)</b> During a fast, the same cells break glycogen back down into glucose.",
  [S("(가) is anabolic and (나) is catabolic.", True,
     "Building a polymer from smaller units is anabolism; breaking it into smaller units is catabolism."),
   S("(가) needs an input of energy, which cells supply by coupling it to ATP or a similar molecule.", True,
     "Anabolic reactions are endergonic. Linking sugars by condensation (Module 2) is driven by coupling it to the hydrolysis of phosphate bonds."),
   S("Since (가) and (나) are reverse processes, running them back to back (glycogen → glucose → glycogen) costs the cell no usable energy.", False,
     "Every conversion loses some usable energy as heat (second law), so cycling between them always costs energy.")],
  "Anabolism vs catabolism · Condensation and hydrolysis (Module 2) · Second law",
  ["anabolism_vs_catabolism", "second_law_direction_entropy", "m2_condensation_hydrolysis"],
  points=3),

# ───────────────────────── ATP & Energetic Coupling ─────────────────────────
combo(AT, "Reading the ATP diagram",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> Each numbered bracket encloses one named molecule.<br><br><b>(나)</b> x, y and z mark three bonds.",
  [S("Bracket 3 encloses ADP, and bracket 2 encloses AMP.", True,
     "Adenine + ribose is adenosine (1); adding one phosphate gives AMP (2), two gives ADP (3), and three gives ATP (4)."),
   S("Hydrolyzing ATP to ADP + Pi breaks bond z.", True,
     "Removing the outermost phosphate breaks the bond between the second and third phosphates: z."),
   S("At physiological pH each phosphate group is negatively charged, so the three phosphates repel one another.", True,
     "That crowding of negative charges is one reason ATP holds so much potential energy and its hydrolysis is exergonic.")],
  "ATP, ADP and AMP · ATP hydrolysis · Charge repulsion",
  ["atp_structure_adp_amp", "atp_phosphate_bonds_energy", "atp_hydrolysis_exergonic_repulsion"],
  points=3, diagram="atp_parts_brackets"),

tf(AT, "Some reactions split ATP into AMP and pyrophosphate (two phosphates still joined together) instead of ADP + Pi.",
  "These reactions break bond y in the diagram rather than bond z.",
  True,
  "AMP keeps only the phosphate nearest the ribose, so the break must come between the first and second phosphates — bond y — releasing the outer two phosphates together as pyrophosphate. RNA polymerase splits each incoming nucleotide the same way (Module 4).",
  "ADP vs AMP · Pyrophosphate release (Module 4)",
  ["atp_structure_adp_amp", "atp_phosphate_bonds_energy", "m4_ntp_energy_polymerization"],
  points=2, diagram="atp_parts_brackets"),

mc(AT, "According to the notes, which feature of ATP best explains why ATP + H2O → ADP + Pi releases energy at physiological pH?",
  "Its negative phosphates repel, so ADP + Pi has less potential energy",
  ["Water is a high-energy molecule that passes its energy on to ATP",
   "The bond between adenine and ribose holds most of ATP's energy",
   "Its phosphates are uncharged and pack tightly, storing energy",
   "The reaction is endergonic, so it takes in energy that the cell can then use"],
  "At physiological pH the phosphates are negatively charged and resist one another; splitting one off relieves that strain, so the products (ADP + Pi) have lower potential energy and the reaction is exergonic (−7.3 kcal/mol).",
  "ATP hydrolysis is exergonic · Ionized phosphates (Module 2)",
  ["atp_hydrolysis_exergonic_repulsion", "atp_phosphate_bonds_energy", "m2_ph_ionization_groups"],
  points=1),

tf(AT, "A sprinter's leg muscles hold only enough ATP for a few seconds of contraction, yet they can keep working far longer.",
  "This works because muscle cells store most of their energy as a large reserve of ATP.",
  False,
  "Cells keep only a small amount of ATP and recycle it constantly: catabolism (breaking down sugars and fats) uses the energy it releases to rebuild ATP from ADP + Pi as fast as it's spent.",
  "ATP is a currency, not long-term storage · Catabolism regenerates ATP",
  ["atp_energy_currency", "anabolism_vs_catabolism"],
  points=1),

combo(AT, "Pushing glucose uphill",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Glucose + Pi → glucose-6-phosphate + H2O, ΔG = +3.3 kcal/mol<br><br><b>(나)</b> ATP + H2O → ADP + Pi, ΔG = −7.3 kcal/mol",
  [S("On its own, (가) is endergonic and does not proceed spontaneously.", True,
     "A positive ΔG means the products have more free energy than the reactants."),
   S("If the phosphate passes directly from ATP to glucose, the overall reaction glucose + ATP → glucose-6-phosphate + ADP has ΔG = −4.0 kcal/mol.", True,
     "ΔG values of coupled reactions add: +3.3 + (−7.3) = −4.0 kcal/mol. The shared phosphate links the two reactions."),
   S("Coupling works because the enzyme lowers (가)'s ΔG from +3.3 to below zero.", False,
     "Enzymes never change ΔG. Coupling works by adding (가) to the more exergonic (나), so the combined ΔG is negative.")],
  "Energetic coupling · Enzymes don't change ΔG",
  ["energetic_coupling_atp", "exergonic_vs_endergonic", "enzyme_lowers_ea_not_delta_g"],
  points=3),

mc(AT, "A biosynthetic step has ΔG = +10.0 kcal/mol. It can be coupled to the hydrolysis of ATP (−7.3 kcal/mol each). What is the smallest number of ATP that must be hydrolyzed to make the overall process spontaneous?",
  "2 ATP, giving a net ΔG of −4.6 kcal/mol",
  ["1 ATP, giving a net ΔG of −2.7 kcal/mol",
   "1 ATP, since +2.7 kcal/mol is close enough",
   "3 ATP, giving a net ΔG of −11.9 kcal/mol",
   "None; an enzyme can lower the ΔG instead"],
  "One ATP gives +10.0 − 7.3 = +2.7 kcal/mol, still positive. Two give +10.0 − 14.6 = −4.6 kcal/mol, which is negative, so the coupled process can proceed. Enzymes don't change ΔG.",
  "Energetic coupling arithmetic",
  ["energetic_coupling_atp", "exergonic_vs_endergonic"],
  points=2),

tf(AT, "A reaction has ΔG = +5.0 kcal/mol. A cell couples it to the hydrolysis of one ATP (ΔG = −7.3 kcal/mol), the two reactions sharing a phosphate intermediate.",
  "The coupled reaction has ΔG = −2.3 kcal/mol, so it proceeds spontaneously.",
  True,
  "ΔG values of coupled reactions add: +5.0 + (−7.3) = −2.3 kcal/mol. A negative net ΔG makes the combined process exergonic.",
  "Energetic coupling",
  ["energetic_coupling_atp", "exergonic_vs_endergonic"],
  points=1),

mc(AT, "Which process does NOT require ATP (or another nucleoside triphosphate) as its energy source?",
  "Glucose diffusing through a carrier, down its gradient",
  ["The Na+/K+ pump moving ions against their gradients",
   "Linking amino acids into a growing polypeptide chain on a ribosome",
   "Moving vesicles along cytoskeleton tracks",
   "Adding nucleotides to a growing RNA strand"],
  "Facilitated diffusion is passive: glucose moves down its gradient, so no ATP is needed (Module 3). Pumping against a gradient, building proteins and RNA, and moving vesicles are all cellular work powered by ATP or other nucleoside triphosphates.",
  "Cellular work · Passive vs active transport (Module 3)",
  ["atp_cellular_work_examples", "atp_energy_currency", "m3_active_transport_atp"],
  points=1),

tf(AT, "Cells regenerate ATP by the reaction ADP + Pi → ATP + H2O.",
  "This reaction has ΔG = −7.3 kcal/mol, the same as ATP hydrolysis, so it runs on its own.",
  False,
  "Reversing a reaction reverses the sign of ΔG: making ATP is +7.3 kcal/mol, endergonic. It happens only when coupled to energy released by catabolism, such as the breakdown of glucose.",
  "Reverse reactions flip the sign of ΔG · Catabolism regenerates ATP",
  ["atp_hydrolysis_exergonic_repulsion", "exergonic_vs_endergonic", "anabolism_vs_catabolism", "gibbs_free_energy_delta_g"],
  points=1),

# ───────────────────────── Thermodynamics & Free Energy ─────────────────────────
combo(TH, "Reading two energy profiles",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> Read all values from the free-energy axes.<br><br><b>(나)</b> Both reactions run at the same temperature, with no enzyme.",
  [S("Reaction I has ΔG = −40 kJ/mol, so it is spontaneous.", True,
     "ΔG = G(products) − G(reactants) = 20 − 60 = −40 kJ/mol: exergonic and thermodynamically favourable."),
   S("Reaction II has the lower activation barrier, so it is the spontaneous one.", False,
     "A low barrier makes a reaction fast, not favourable. Reaction II's products sit above its reactants (ΔG = 50 − 30 = +20 kJ/mol), so it is endergonic."),
   S("The reverse of reaction II would have ΔG = −20 kJ/mol and an activation barrier of only 5 kJ/mol.", True,
     "Run backward, II starts at 50 and ends at 30 (−20 kJ/mol), and the climb from 50 to the peak at 55 is just 5 kJ/mol.")],
  "ΔG from free-energy profiles · Spontaneous ≠ fast · Activation energy",
  ["exergonic_vs_endergonic", "gibbs_free_energy_delta_g", "activation_energy_transition_state"],
  points=3, diagram="reaction_profiles_two"),

tf(TH, "Reaction I in the diagram has a large, negative ΔG.",
  "So reaction I will proceed rapidly on its own as soon as the reactants are mixed.",
  False,
  "ΔG tells whether a reaction can run on its own, not how fast. Reaction I must first climb a 50 kJ/mol activation barrier (60 → 110), which can make it very slow without a catalyst.",
  "Spontaneous ≠ fast · Activation energy",
  ["exergonic_vs_endergonic", "activation_energy_transition_state", "enzyme_lowers_ea_not_delta_g"],
  points=1, diagram="reaction_profiles_two"),

mc(TH, "Using the diagram, what is reaction I's activation energy in the forward direction, and what would it be for the reverse reaction?",
  "50 kJ/mol forward; 90 kJ/mol reverse",
  ["110 kJ/mol forward; 90 kJ/mol reverse",
   "50 kJ/mol in both directions",
   "40 kJ/mol forward; 50 kJ/mol reverse",
   "90 kJ/mol forward; 50 kJ/mol reverse"],
  "Activation energy is the climb from the starting level to the peak: forward 110 − 60 = 50 kJ/mol; in reverse, starting from the products, 110 − 20 = 90 kJ/mol. The reverse barrier is larger by exactly the size of ΔG (40 kJ/mol).",
  "Activation energy · Transition state",
  ["activation_energy_transition_state", "gibbs_free_energy_delta_g"],
  points=2, diagram="reaction_profiles_two"),

tf(TH, "A growing cell builds highly ordered proteins and membranes from simpler, more disordered molecules.",
  "This doesn't violate the second law, because the cell releases heat and simple waste molecules that increase the entropy of its surroundings by more.",
  True,
  "The second law applies to the cell plus its surroundings. Order inside is paid for with energy from food or light, much of it released as heat and as CO2 and water, so total entropy still rises.",
  "The second law and living systems · Entropy",
  ["second_law_direction_entropy", "anabolism_vs_catabolism"],
  points=2),

mc(TH, "Muscle converts the chemical energy of glucose into movement with roughly 25% efficiency. What happens to the other 75%?",
  "It's released mostly as heat, raising entropy; none is destroyed",
  ["It's destroyed during the conversion, exactly as the second law states",
   "It stays stored in the muscle as a reserve of extra ATP",
   "It's converted back into glucose for later use",
   "It leaves the muscle mostly in the form of light"],
  "First law: energy is conserved, only converted. Second law: no conversion is 100% efficient, and the 'lost' energy is mostly heat that increases entropy — which is why exercise warms you and shivering keeps you warm.",
  "First and second laws · Real-world: body heat",
  ["first_law_conservation", "second_law_direction_entropy"],
  points=1),

tf(TH, "Dissolving the salt in an instant cold pack (ammonium nitrate) absorbs heat, with ΔH = +26 kJ/mol, but greatly increases disorder: TΔS = +33 kJ/mol at room temperature.",
  "ΔG for dissolving is −7 kJ/mol, so it happens spontaneously even though it absorbs heat.",
  True,
  "ΔG = ΔH − TΔS = +26 − 33 = −7 kJ/mol. A large enough increase in entropy can make a heat-absorbing process spontaneous.",
  "ΔG = ΔH − TΔS · Real-world: cold packs",
  ["delta_g_enthalpy_entropy", "exergonic_vs_endergonic"],
  points=2),

mc(TH, "A reaction has ΔH = −20 kJ/mol and makes things more ordered (ΔS < 0). Using ΔG = ΔH − TΔS, what happens to its ΔG as temperature rises?",
  "ΔG becomes less negative and eventually positive",
  ["ΔG becomes more negative, since heat speeds up every reaction",
   "ΔG doesn't change, since only ΔH determines ΔG",
   "ΔG becomes more negative, because T is measured in kelvin",
   "The reaction becomes spontaneous only above some temperature"],
  "With ΔS negative, the −TΔS term is positive and grows with T, eating into the favourable ΔH, so the reaction is spontaneous only below some temperature. (Temperature also changes reaction speed, but that's about activation energy, not ΔG.)",
  "ΔG = ΔH − TΔS · Temperature and entropy",
  ["delta_g_enthalpy_entropy"],
  points=2),

tf(TH, "In the blood, CO2 + H2O ⇌ H2CO3 (carbonic acid). During hard exercise, working muscles release more CO2 into the blood.",
  "The extra CO2 pushes this reaction back toward CO2 and water, raising the blood's pH.",
  False,
  "Adding a reactant pushes a reversible reaction forward: more CO2 makes more H2CO3, which releases H+ (Module 2) and lowers the blood's pH slightly. The concentrations of reactants and products set the direction.",
  "Concentrations set reaction direction · Acids and pH (Module 2)",
  ["concentration_direction_reversible", "chemical_reaction_bonds_change", "m2_ph_ionization_groups"],
  points=1),

tf(TH, "The reaction A → B in a pathway has a positive ΔG when A and B are present at equal concentrations.",
  "A cell can still keep A → B running forward by keeping A plentiful and quickly using up B in the next step.",
  True,
  "The notes give two ways cells run +ΔG reactions. One is to keep the reactant-to-product ratio above its equilibrium value — here by supplying A and draining B. The other is coupling to an exergonic reaction.",
  "Running +ΔG reactions: concentrations · Metabolic pathways",
  ["positive_delta_g_concentrations", "metabolism_definition_pathways", "concentration_direction_reversible"],
  points=2),

tf(TH, "A gazelle absorbs energy from the grass it eats. That energy ends up as movement, body heat, and chemical bonds in its tissues.",
  "Since much of it ends up as heat, the total energy in these forms is less than the energy absorbed; the rest was destroyed.",
  False,
  "First law: energy is never destroyed. Movement + heat + stored chemical energy add up to everything absorbed. Heat is just the least useful form (second law), not missing energy.",
  "First law: conservation of energy",
  ["first_law_conservation", "potential_vs_kinetic_energy", "second_law_direction_entropy"],
  points=1),

tf(TH, "Chlorophyll extracted from leaves glows red when lit in a test tube: its excited electrons drop back to lower energy levels with no chloroplast machinery to capture the energy.",
  "The red glow is the energy given off as the electrons fall back, which shows the energy is converted rather than destroyed.",
  True,
  "When electrons move from higher to lower energy levels, the energy is released as heat or light — converted, not lost (first law). Inside a chloroplast, that same energy would be captured to make ATP and sugar instead.",
  "Electrons dropping release energy · First law",
  ["electrons_drop_release_energy", "first_law_conservation"],
  points=1),

mc(TH, "In CO2 + H2O → H2CO3, which description of the bonds is correct?",
  "One C–O bond of CO2 and one O–H of water break; new C–O and O–H bonds form",
  ["Every bond in both molecules breaks, and the atoms recombine at random",
   "Water's bonds stay intact while the whole H2O molecule bonds to the carbon",
   "Some of the carbon atoms are converted into oxygen atoms along the way",
   "No bonds break; the two molecules simply cling by hydrogen bonds"],
  "Atoms keep their identity; only bonds change. In the notes' example, one of the bonds between C and O in CO2 and one O–H bond in water break, and new bonds form between CO2's carbon and water's oxygen and between a CO2 oxygen and water's hydrogen.",
  "Chemical reactions rearrange bonds, not atoms",
  ["chemical_reaction_bonds_change"],
  points=1),

tf(TH, "In glycolysis, one step has a positive ΔG under standard conditions, yet it runs forward inside cells.",
  "This is possible because the enzyme for that step can make its ΔG negative.",
  False,
  "Enzymes never change ΔG; they only lower the activation energy. The step runs forward because the next enzyme keeps using up its product, holding the product concentration low (other steps are pushed along by coupling to ATP).",
  "Running +ΔG reactions · Enzymes don't change ΔG",
  ["positive_delta_g_concentrations", "enzyme_lowers_ea_not_delta_g", "metabolism_definition_pathways"],
  points=1),

mc(TH, "A firefly's light comes from a reaction that leaves a product molecule with an electron raised to a higher energy level. What actually produces the light?",
  "The excited electron falling back, releasing energy as light",
  ["New energy being created as the reaction's product bonds form",
   "Heat from the reaction making the insect's tissues glow",
   "ATP being converted directly into light with no energy lost",
   "Electrons being destroyed, releasing their energy as light"],
  "When an electron moves from a higher to a lower energy level, the difference is released as heat or light — here, mostly light. Chemical energy is converted into light energy, not created, and electrons aren't destroyed (first law); some energy is still lost as heat (second law).",
  "Electrons dropping release energy · First law · Real-world: fireflies",
  ["electrons_drop_release_energy", "first_law_conservation"],
  points=1),

match(TH, "Which way does the energy flow?",
  "Match each process to the description of its energetics.",
  "Process", "Energetics",
  [("Building a protein from amino acids", "Endergonic; joins monomers into a polymer (anabolic)"),
   ("Oxidizing glucose to CO2 and water", "Exergonic; catabolic, and its energy is used to remake ATP"),
   ("ATP + H2O → ADP + Pi", "Exergonic: ΔG = −7.3 kcal/mol"),
   ("ADP + Pi → ATP + H2O", "Endergonic: ΔG = +7.3 kcal/mol"),
   ("Glucose + ATP → glucose-6-phosphate + ADP", "Coupled reaction with a negative net ΔG")],
  "Anabolic building needs energy (+ΔG); catabolic breakdown releases it (−ΔG), and cells capture some of it to remake ATP. ATP hydrolysis (−7.3 kcal/mol) is the exergonic half that cells couple to endergonic steps; running it in reverse flips the sign to +7.3; and adding the coupled ΔG values (+3.3 − 7.3) gives −4.0 kcal/mol.",
  "Exergonic vs endergonic · Anabolism vs catabolism · Coupling",
  ["exergonic_vs_endergonic", "anabolism_vs_catabolism", "energetic_coupling_atp", "atp_hydrolysis_exergonic_repulsion"],
  points=3),

# ───────────────────────── Enzymes & Their Regulation ─────────────────────────
combo(EN, "Two paths, one reaction",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> Curves 1 and 2 show the same reaction, with and without an enzyme.<br><br><b>(나)</b> a, b and c mark three energy differences.",
  [S("Curve 2 is the enzyme-catalyzed path; adding the enzyme replaces barrier a with the smaller barrier b.", True,
     "Enzymes speed reactions by lowering the activation energy needed to reach the transition state."),
   S("c is the same for both curves, so the enzyme doesn't change how much free energy the reaction releases.", True,
     "c is ΔG, set by the reactant and product levels; it is the same with and without an enzyme."),
   S("Because the enzyme is a folded protein, heating it until it unfolds would return the reaction to curve 1.", True,
     "The lower barrier depends on the active site, which exists only in the folded protein; a denatured enzyme no longer catalyzes (Module 5).")],
  "Enzymes lower activation energy · ΔG unchanged · Active site needs folding (Module 5)",
  ["enzyme_lowers_ea_not_delta_g", "activation_energy_transition_state", "enzymes_are_proteins_active_site", "tertiary_functional_form_active_site"],
  points=3, diagram="enzyme_energy_profile"),

tf(EN, "In the diagram, c marks the free-energy difference between the reactants and the products.",
  "So this reaction is endergonic, and the enzyme supplies the energy it needs to proceed.",
  False,
  "Products below reactants means a negative ΔG: the reaction is exergonic. Enzymes don't supply energy or change ΔG; they only lower the barrier (a → b).",
  "Reading ΔG from a profile · What enzymes do",
  ["exergonic_vs_endergonic", "enzyme_lowers_ea_not_delta_g"],
  points=1, diagram="enzyme_energy_profile"),

combo(EN, "Three encounters at the enzyme",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> X resembles the substrate in shape.<br><br><b>(나)</b> Y binds away from the active site and changes the enzyme's shape.",
  [S("Adding a large excess of substrate could reduce X's effect, because substrate and X compete for the same site.", True,
     "X is a competitive inhibitor: the more substrate there is, the more often substrate rather than X wins the active site."),
   S("Extra substrate would overcome Y's effect just as well, since Y also blocks the active site directly.", False,
     "Y is a noncompetitive inhibitor: it binds elsewhere and distorts the active site, so adding substrate can't push it out."),
   S("If X binds only briefly and then falls off, its inhibition is reversible.", True,
     "Inhibitors that bind and come off again are reversible; those that bind permanently are irreversible.")],
  "Competitive vs noncompetitive inhibition · Reversible vs irreversible",
  ["competitive_vs_noncompetitive", "inhibitors_reversible_irreversible", "active_site_binds_stabilizes_ts"],
  points=3, diagram="inhibition_modes"),

tf(EN, "Aspirin permanently attaches a small chemical group (an acetyl group) to an amino acid in the active site of the COX enzyme, which helps make inflammatory signals.",
  "Aspirin is therefore an irreversible inhibitor: the affected enzyme molecules stay inactive until the cell makes new ones.",
  True,
  "A covalent change to the active site doesn't wear off, so the enzyme stays blocked; only newly made COX restores activity. Blood platelets have no nucleus and can't make new COX, which is why one aspirin's effect on them lasts for days.",
  "Irreversible inhibition · Real-world: aspirin",
  ["inhibitors_reversible_irreversible", "enzymes_are_proteins_active_site"],
  points=2),

mc(EN, "Methanol poisoning is treated with ethanol. Both are substrates of the same liver enzyme, which turns methanol into a toxic product. Which panel of the diagram best shows how ethanol helps?",
  "Panel 2: ethanol competes with methanol for the active site",
  ["Panel 3: ethanol binds elsewhere on the enzyme and reshapes it",
   "Panel 1: ethanol helps methanol fit into the active site",
   "Panel 3: ethanol permanently destroys the enzyme",
   "Panel 2: ethanol binds permanently, so no product forms"],
  "Ethanol and methanol fit the same active site, so plenty of ethanol keeps the enzyme busy (competitive inhibition) and slows toxic-product formation while the kidneys clear the methanol. Ethanol eventually leaves the site: the effect is reversible.",
  "Competitive inhibition · Real-world: methanol poisoning",
  ["competitive_vs_noncompetitive", "inhibitors_reversible_irreversible"],
  points=2, diagram="inhibition_modes"),

combo(EN, "Brakes on a branched pathway",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> D inhibits e2, the first enzyme on D's own branch.<br><br><b>(나)</b> F inhibits e4, the first enzyme on F's own branch.",
  [S("When D is plentiful, B can still be used to make E and F instead of being spent on more D.", True,
     "Blocking e2 shuts only D's branch; B remains available to e4, so making F continues."),
   S("If D instead inhibited e1, a surplus of D would leave the making of F unaffected.", False,
     "e1 makes B, which both branches need. Inhibiting e1 would starve the F branch too — which is why feedback usually targets the first step after a branch."),
   S("D must bind e2's active site in place of B, since feedback inhibition is a kind of competitive inhibition.", False,
     "End products usually look nothing like the first substrate; they typically bind a separate (allosteric) site and change the enzyme's shape, as isoleucine does to threonine dehydratase.")],
  "Feedback inhibition · Allosteric enzymes · Metabolic pathways",
  ["feedback_inhibition_allosteric", "metabolism_definition_pathways", "competitive_vs_noncompetitive"],
  points=3, diagram="branched_pathway"),

tf(EN, "Isoleucine, the end product of a five-step pathway that starts from threonine, binds the pathway's first enzyme (threonine dehydratase) at a site separate from its active site.",
  "When isoleucine runs low, threonine dehydratase stays inhibited, because this kind of inhibition can't be reversed.",
  False,
  "Allosteric feedback inhibition is reversible: as isoleucine is used up, it leaves the enzyme, the enzyme reactivates, and the pathway makes more. That's how the pathway matches supply to demand without wasting energy.",
  "Feedback inhibition is reversible · Allosteric regulation",
  ["feedback_inhibition_allosteric", "inhibitors_reversible_irreversible"],
  points=1),

mc(EN, "In a single-chain enzyme, the three amino acids that form the active site are numbers 40, 95 and 210 in the sequence. How can residues so far apart work together?",
  "Folding brings them together in three-dimensional space",
  ["Peptide bonds link them directly to one another",
   "They lie next to each other in the primary structure",
   "Each one comes from a different subunit",
   "They pair with each other through hydrogen-bonded bases"],
  "The active site is formed by specific amino acids, often far apart in the sequence, that tertiary folding places side by side. Unfold the chain and the active site disappears.",
  "Active site formed by folding · Tertiary structure (Module 5)",
  ["enzymes_are_proteins_active_site", "tertiary_functional_form_active_site"],
  points=1),

tf(EN, "When glucose binds hexokinase, the enzyme's two lobes swing closed around it like a clamp.",
  "This fits the lock-and-key model better than induced fit, since the enzyme ends up perfectly shaped around glucose.",
  False,
  "In the lock-and-key model the site already has the right shape. Hexokinase changes shape when glucose binds — the defining feature of induced fit.",
  "Induced fit vs lock-and-key",
  ["lock_key_vs_induced_fit", "active_site_binds_stabilizes_ts"],
  points=1),

mc(EN, "One molecule of an enzyme can convert thousands of substrate molecules per second. Which feature of the cycle E + S ⇌ ES ⇌ EP ⇌ E + P makes this possible?",
  "The enzyme is released unchanged at the end of each cycle",
  ["The enzyme becomes part of each product molecule",
   "Each cycle transfers energy from the enzyme to the substrate",
   "The enzyme makes ΔG more negative, so products form instantly",
   "The ES complex is permanent, so binding never has to repeat"],
  "After converting substrate to product in the active site, the enzyme lets the product go (EP → E + P) and is free to bind the next substrate. It is a catalyst: not consumed, not a source of energy, and no change to ΔG.",
  "The enzyme–substrate cycle · Catalysts aren't consumed",
  ["enzyme_catalysis_anabolic_catabolic", "active_site_binds_stabilizes_ts"],
  points=1),

tf(EN, "Carbonic anhydrase speeds up CO2 + H2O → H2CO3 in body tissues and H2CO3 → CO2 + H2O in the lungs.",
  "One enzyme speeds both directions because it lowers the barrier for the forward and reverse reactions alike, while concentrations decide which way the reaction runs.",
  True,
  "An enzyme lowers the transition-state peak, which both directions must cross. Where CO2 is high (tissues) the reaction runs forward; where CO2 is being breathed out (lungs) it runs backward.",
  "Enzymes speed both directions · Concentrations set direction",
  ["enzyme_lowers_ea_not_delta_g", "concentration_direction_reversible", "enzyme_catalysis_anabolic_catabolic"],
  points=2),

match(EN, "What explains it?",
  "Match each observation about an enzyme to the explanation that fits.",
  "Observation", "Explanation",
  [("Boiling an enzyme destroys its activity for good", "Heat unfolds the chain, destroying the active site"),
   ("Mercury ions bond permanently to the enzyme's cysteines", "Irreversible inhibition"),
   ("A pathway's end product shuts down its first enzyme", "Feedback inhibition of an allosteric enzyme"),
   ("A substrate look-alike slows the reaction, but extra substrate overcomes it", "Competitive inhibition"),
   ("A molecule binding away from the active site makes the enzyme work faster", "An activator")],
  "Activity depends on the folded active site, which heat destroys. Permanent bonding = irreversible inhibition; product-triggered shutdown = feedback inhibition at an allosteric site; look-alikes compete for the active site; activators increase activity.",
  "Enzyme regulation · The active site needs folding",
  ["enzymes_are_proteins_active_site", "inhibitors_reversible_irreversible", "feedback_inhibition_allosteric", "competitive_vs_noncompetitive"],
  points=3),

tf(EN, "Some drugs are designed to resemble a reaction's transition state rather than its substrate.",
  "Such drugs bind an enzyme's active site even more tightly than the substrate does, since the active site is shaped to stabilize the transition state.",
  True,
  "Enzymes lower activation energy by binding and stabilizing the transition state. A stable look-alike of that state fits the active site best of all and blocks it — the design idea behind several drugs.",
  "The active site stabilizes the transition state",
  ["active_site_binds_stabilizes_ts", "activation_energy_transition_state"],
  points=2),

mc(EN, "Which observation supports the induced-fit model rather than the lock-and-key model?",
  "The enzyme's shape changes measurably when the substrate binds",
  ["The substrate already fits the active site exactly before it binds",
   "The enzyme acts on only one particular substrate",
   "The enzyme speeds the reaction without being used up",
   "ΔG is the same with and without the enzyme"],
  "Both models explain specificity and catalysis; what sets induced fit apart is that binding itself reshapes the enzyme around the substrate. A perfect pre-existing fit is the lock-and-key picture.",
  "Induced fit vs lock-and-key",
  ["lock_key_vs_induced_fit"],
  points=1),
]

for _c in CARDS:
    _c["mod"] = MOD
