from cardkit import S, combo, match, tf, mc

MOD = 5
TM = "Translation Machinery & Genetic Code"
TP = "Translation Stages: Prok vs Euk"
SO = "Regulation & Protein Sorting"

CARDS = [
# ───────────────────────── Translation Machinery & Genetic Code ─────────────────────────
combo(TM, "From gene to anticodon",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> The four rows show one codon's worth of a gene, its mRNA and the tRNA that reads it.<br><br><b>(나)</b> Unlabelled sequences are written 5'→3'.",
  [S("Written in the standard 5'→3' direction, the anticodon is UGC.", True,
     "The anticodon is 3'-CGU-5'; read from its 5' end it is 5'-UGC-3'."),
   S("For a different gene whose template strand reads 3'-TAC-5', the tRNA that reads its codon has the anticodon 3'-UAC-5'.", True,
     "Template 3'-TAC-5' → mRNA codon 5'-AUG-3' → anticodon 3'-UAC-5': the anticodon repeats the template strand, with U for T, because both are complementary to the codon."),
   S("A tRNA with this anticodon would also pair with the codon 5'-ACG-3'.", False,
     "Pairing must be antiparallel. Matching 5'-UGC-3' base by base in the same direction gives ACG, but antiparallel pairing matches 3'-CGU-5' to 5'-GCA-3', not to ACG.")],
  "Codon–anticodon pairing is antiparallel · Template strand (Module 4)",
  ["codon_anticodon_antiparallel", "m4_template_coding_strands"],
  points=3, diagram="trna_codon_pairing"),

tf(TM, "In the diagram, the middle base of the DNA template strand (G) is mutated to A. (GCA = Ala, GUA = Val, GAA = Glu)",
  "The mRNA codon becomes GUA, so the protein carries valine in place of alanine.",
  True,
  "The template's middle base pairs with the codon's middle base. Template G → A means the mRNA gets U instead of C: GCA becomes GUA, which codes for Val. One base change in the gene, one amino acid change in the protein.",
  "Template strand → codon → amino acid",
  ["codon_triplet_nonoverlapping", "central_dogma_translation_final", "m4_template_coding_strands"],
  points=2, diagram="trna_codon_pairing"),

mc(TM, "Using the genetic code table, which single-base change in the mRNA codon CUU would NOT change the amino acid?",
  "CUU → CUC",
  ["CUU → CCU",
   "CUU → AUU",
   "CUU → CAU",
   "CUU → UUU"],
  "CUU and CUC both code for Leu. The others give Pro (CCU), Ile (AUU), His (CAU) and Phe (UUU). Third-position changes are the ones most often silent, because the code is redundant: many amino acids have codons that differ only in their third base.",
  "Redundancy of the genetic code · Silent changes",
  ["genetic_code_64_redundant", "codon_triplet_nonoverlapping"],
  points=1, diagram="genetic_code_table"),

tf(TM, "Using the genetic code table, count the codons for each amino acid.",
  "Every amino acid is encoded by at least two codons, which is what makes the code redundant.",
  False,
  "Methionine (AUG) and tryptophan (UGG) each have only one codon. The code is still redundant because most amino acids have two to six codons: 61 coding codons for 20 amino acids.",
  "Redundancy of the genetic code · AUG start codon",
  ["genetic_code_64_redundant", "start_stop_codons"],
  points=1, diagram="genetic_code_table"),

mc(TM, "Using the genetic code table, a ribosome starts at the first AUG of the mRNA 5'-CCAUGGUUCAUUGAGC-3'. What polypeptide is made?",
  "Met–Val–His (3 amino acids)",
  ["Met–Val–His–Trp (4 amino acids)",
   "Pro–Trp–Phe–Ile–Glu (5 amino acids)",
   "Met–Val (2 amino acids)",
   "Met–Val–His–Stop (4 amino acids)"],
  "Starting at AUG sets the reading frame: AUG (Met) GUU (Val) CAU (His) UGA (stop). A stop codon has no amino acid (and UGA is not UGG, Trp), so the chain is 3 long. Reading from the first base would give a different frame (CCA UGG UUC…) and a different protein.",
  "Start codon sets the reading frame · Stop codons",
  ["start_stop_codons", "reading_frame", "codon_triplet_nonoverlapping"],
  points=2, diagram="genetic_code_table"),

mc(TM, "In a gene of 300 codons, one nucleotide is inserted just after codon 5, and one nucleotide is deleted from codon 9. Assuming no stop codon appears along the way, what protein is made?",
  "Codons 6–9 are misread, but the frame is restored from codon 10 on",
  ["Every codon after the insertion is misread, so the rest is garbled",
   "Nothing changes, because the insertion and deletion cancel out",
   "Only codons 6 and 9 change; the codons between them are normal",
   "The chain ends at codon 5, since an extra base acts as a stop signal"],
  "Codons are read three at a time from a fixed start. The insertion shifts the frame, so codons 6–9 are read wrongly; the deletion shifts it back, so codon 10 onward is read normally. Crick and Brenner used exactly this kind of experiment in 1961 to show that the code is read as nonoverlapping triplets.",
  "Reading frame · Nonoverlapping triplets · Real-world: Crick and Brenner's experiment",
  ["reading_frame", "codon_triplet_nonoverlapping"],
  points=2),

combo(TM, "Freeze-frame on a ribosome",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> UGG codes for Trp and AAA for Lys; UAG is a stop codon.<br><br><b>(나)</b> The ribosome will keep translating this mRNA until the polypeptide is finished.",
  [S("The incoming tRNA marked ? must carry the anticodon 3'-ACC-5' and the amino acid Trp.", True,
     "The A site holds codon 5'-UGG-3'; its antiparallel partner is 3'-ACC-5', and the tRNA with that anticodon is charged with Trp."),
   S("The finished polypeptide will be Met–Ala–Trp–Lys, with Met at its N-terminus.", True,
     "AUG GCU UGG AAA, then UAG (stop): Met–Ala–Trp–Lys. Met, the first amino acid, keeps the free amino group."),
   S("The tRNA in the E site is uncharged and is about to leave the ribosome.", True,
     "It delivered Met, passed it on when the first peptide bond formed, and now exits empty from the E site.")],
  "A, P and E sites · Codon–anticodon pairing · Start and stop codons",
  ["ribosome_a_p_e_sites", "codon_anticodon_antiparallel", "start_stop_codons", "n_terminus_c_terminus"],
  points=3, diagram="ribosome_snapshot"),

mc(TM, "In the diagram, which way is the ribosome moving along the mRNA, and how can you tell?",
  "Toward 3': AUG, the first codon read, is now under the E site",
  ["Toward 5': the empty A site marks where the ribosome has just been",
   "Toward 5': Met at the chain's free end was the last amino acid added",
   "Toward 3': the large subunit always sits on the mRNA's 3' side",
   "It stays put while the mRNA slides back and forth through it"],
  "Ribosomes read mRNA 5'→3'. The start codon AUG, read first, is now under the E site, and the unread codons lie on the 3' side. Met at the chain's free end was the first amino acid added, not the last, which also shows the ribosome began at the 5' end.",
  "Ribosomes move 5'→3' · A, P and E sites · The N-terminus is made first",
  ["ribosome_moves_5_to_3", "ribosome_a_p_e_sites", "n_terminus_c_terminus"],
  points=2, diagram="ribosome_snapshot"),

tf(TM, "In a classic experiment, the cysteine already attached to a charged tRNA-Cys was chemically converted to alanine, leaving the tRNA's anticodon unchanged. The tRNA was then added to a protein-making system.",
  "Alanine was inserted at cysteine codons, because the ribosome checks only codon–anticodon pairing, not which amino acid the tRNA carries.",
  True,
  "tRNAs are adapters: the anticodon reads the codon, and the amino acid simply rides along. That's why the accuracy of aminoacyl tRNA synthetases, which load each tRNA with the right amino acid, matters so much.",
  "tRNAs as adapters · Accuracy depends on tRNA synthetases",
  ["trna_adapter_structure"],
  points=2),

tf(TM, "A cell runs short of free leucine, so many tRNAs whose anticodons read leucine codons stay uncharged.",
  "Ribosomes can skip the leucine codons and keep going in frame, making shorter proteins that lack leucine.",
  False,
  "An uncharged tRNA has no amino acid to deliver. A ribosome that reaches a leucine codon waits, with that codon in its A site, until a charged tRNA arrives; it doesn't skip codons.",
  "Charged vs uncharged tRNA · The A site",
  ["aminoacyl_trna_synthetase_charging", "ribosome_a_p_e_sites"],
  points=2),

match(TM, "Which component is responsible?",
  "Match each observation to the translation component that best explains it.",
  "Observation", "Component",
  [("A mutant tyrosine tRNA inserts tyrosine at UAG stop codons, so some chains run on past them", "The tRNA's anticodon"),
   ("A tRNA is loaded with the wrong amino acid but still pairs with the correct codon", "An aminoacyl tRNA synthetase"),
   ("An antibiotic binds rRNA in the large subunit and blocks peptide bond formation", "The peptidyl transferase center"),
   ("In an extract missing one protein, finished chains stay attached to tRNAs at stop codons", "The release factor"),
   ("In a human cell extract missing one group of proteins, small subunits never bind capped mRNAs", "Eukaryotic initiation factors")],
  "Each component has one job: the anticodon decides which codon a tRNA reads (here, a mutant anticodon pairs with UAG); synthetases load the right amino acid; the rRNA peptidyl transferase center joins amino acids; release factors free the finished chain at a stop codon; eukaryotic initiation factors bring the small subunit to the 5' cap.",
  "Components of translation",
  ["translation_components", "trna_adapter_structure", "aminoacyl_trna_synthetase_charging", "elongation_steps_peptidyl_transferase", "termination_release_factor", "euk_initiation_cap_scanning"],
  points=3),

mc(TM, "The standard genetic code has 64 codons. How many of them are read by tRNAs carrying an amino acid?",
  "61",
  ["64",
   "20",
   "60",
   "63"],
  "Three codons (UAA, UAG, UGA) are stop codons: no tRNA reads them, and a release factor binds instead. That leaves 61 codons for 20 amino acids, so most amino acids have several codons.",
  "Stop codons · A redundant code",
  ["start_stop_codons", "genetic_code_64_redundant", "termination_release_factor"],
  points=1),

tf(TM, "Suppose codons overlapped, so that bases 1-2-3, then 2-3-4, then 3-4-5 were each read as a codon.",
  "A single base substitution would then change up to three neighbouring codons at once, whereas in the real code it changes only the one codon that contains it.",
  True,
  "In an overlapping code each base belongs to three codons. Real codons are a nonoverlapping series of triplets, so each base sits in exactly one codon, and a substitution changes only that codon.",
  "Nonoverlapping triplets",
  ["codon_triplet_nonoverlapping"],
  points=2),

mc(TM, "A mutation in a cell's rRNA genes changes the amino acid sequence of no protein, yet it slows protein synthesis throughout the cell. Which explanation fits best?",
  "rRNA builds the ribosome itself, so every ribosome works more slowly",
  ["rRNA carries amino acids to the ribosome, so fewer arrive at each codon",
   "rRNA is the template for every mRNA, so all mRNAs are made more slowly",
   "rRNA forms the 5' cap of each mRNA, so fewer mRNAs are recognized",
   "rRNA pairs with each codon in place of tRNA, so codons are read slowly"],
  "Only mRNA is translated. rRNA is transcribed from DNA but works as RNA: with ribosomal proteins it builds both ribosomal subunits, and it forms the peptidyl transferase center. A faulty rRNA slows every ribosome without changing any protein's sequence. Carrying amino acids and pairing with codons are tRNA's jobs.",
  "Central dogma · Noncoding RNAs · Ribosomes are RNA + protein",
  ["central_dogma_translation_final", "ribosome_rna_protein_subunits", "gene_expression_overview_euk", "m4_rna_types"],
  points=2),

tf(TM, "Translation is the last step in the flow of information from DNA to protein.",
  "Given a protein's amino acid sequence, you could work out the exact mRNA sequence that coded for it.",
  False,
  "The code is redundant: most amino acids have two to six codons, so one protein sequence fits many possible mRNAs. Information can be read from codon to amino acid, but not reconstructed exactly the other way.",
  "Redundancy of the code · Central dogma",
  ["central_dogma_translation_final", "genetic_code_64_redundant"],
  points=2),

tf(TM, "A student is asked for the anticodon that pairs with the mRNA codon 5'-CAG-3'.",
  "Pairing base by base gives GUC, so written 5'→3' the anticodon is 5'-GUC-3'.",
  False,
  "Pairing is antiparallel: the codon's first (5') base pairs with the anticodon's last (3') base. The anticodon is 3'-GUC-5', which written 5'→3' is 5'-CUG-3'.",
  "Codon–anticodon pairing is antiparallel",
  ["codon_anticodon_antiparallel"],
  points=1),

# ───────────────────────── Translation Stages: Prok vs Euk ─────────────────────────
combo(TP, "Where can a ribosome start?",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> Each coding bar is read from its AUG to the stop codon that follows.<br><br><b>(나)</b> The inner AUG of mRNA 1 lies in the same reading frame as its first AUG.",
  [S("mRNA 2 can yield three separate polypeptides, because a ribosome can bind at each AGGAGGU and start at the AUG after it.", True,
     "Each coding region has its own Shine-Dalgarno sequence (AGGAGGU) upstream of its AUG, so one bacterial mRNA can code for several polypeptides."),
   S("On mRNA 1, translation starts at the first AUG after the cap, and the inner AUG is read as methionine within the same polypeptide.", True,
     "The initiation complex assembles at the 5' cap and scans to the first AUG; a later AUG in the same frame simply codes for Met inside the chain."),
   S("mRNA 1 comes from a bacterium, since it ends in a tail of A's.", False,
     "A 5' cap and a poly(A) tail are eukaryotic processing marks (Module 4). Bacterial mRNAs have no cap; mRNA 2's Shine-Dalgarno sequences mark it as bacterial.")],
  "Cap and scanning vs Shine-Dalgarno · Polycistronic mRNA",
  ["prok_initiation_shine_dalgarno", "polycistronic_mrna", "euk_initiation_cap_scanning", "m4_mrna_processing_cap_tail_splicing"],
  points=3, diagram="translation_start_prok_euk"),

tf(TP, "A researcher deletes only the first AGGAGGU sequence of mRNA 2 in the diagram.",
  "The first polypeptide stops being made, while the second and third are still translated.",
  True,
  "In bacteria, each coding region's own Shine-Dalgarno sequence recruits a ribosome, which starts at the next AUG. Removing the first one blocks only the first region; the other two keep their binding sites.",
  "Shine-Dalgarno sequence · Polycistronic mRNA",
  ["prok_initiation_shine_dalgarno", "polycistronic_mrna"],
  points=2, diagram="translation_start_prok_euk"),

tf(TP, "mRNA 1 in the diagram is added to a bacterial extract containing bacterial ribosomes and translation factors, but no eukaryotic initiation factors.",
  "The bacterial ribosomes can bind the cap and start translating at mRNA 1's first AUG.",
  False,
  "Bacterial ribosomes find start sites by pairing with Shine-Dalgarno sequences, not caps, and mRNA 1 has none. That's why genes moved into bacteria are given a bacterial ribosome-binding sequence upstream of the AUG.",
  "Shine-Dalgarno vs cap-dependent initiation",
  ["prok_initiation_shine_dalgarno", "euk_initiation_cap_scanning", "translation_components"],
  points=2, diagram="translation_start_prok_euk"),

mc(TP, "Put these events of eukaryotic translation in order: (1) the large subunit joins; (2) the small subunit, initiation factors and Met-tRNA bind at the 5' cap; (3) the complex scans to the first AUG; (4) the first peptide bond forms.",
  "2 → 3 → 1 → 4",
  ["3 → 2 → 1 → 4",
   "2 → 1 → 3 → 4",
   "1 → 2 → 3 → 4",
   "2 → 3 → 4 → 1"],
  "The small subunit with Met-tRNA and initiation factors loads at the cap and scans; only when it reaches AUG does the large subunit join (and the factors leave). Peptide bonds form in the large subunit, so the first one comes last.",
  "Eukaryotic initiation · Stages of translation",
  ["euk_initiation_cap_scanning", "translation_three_stages", "elongation_steps_peptidyl_transferase"],
  points=2),

tf(TP, "In the diagram, Met–Ala is attached to the tRNA in the P site, and a charged tRNA now enters the A site.",
  "When the next peptide bond forms, the new amino acid is added onto the chain, which stays attached to the P-site tRNA.",
  False,
  "The reverse: the whole chain is transferred from the P-site tRNA onto the amino acid carried by the A-site tRNA. The chain (now Met–Ala–Trp) hangs from the A-site tRNA until the ribosome shifts one codon and moves that tRNA into the P site.",
  "Elongation: transfer to the A-site tRNA · Translocation",
  ["elongation_steps_peptidyl_transferase", "translocation_one_codon", "ribosome_a_p_e_sites"],
  points=2, diagram="ribosome_snapshot"),

mc(TP, "In the diagram, a tRNA enters the A site, a peptide bond forms, and the ribosome then shifts one codon. Which codons now sit in the E, P and A sites?",
  "E: GCU, P: UGG, A: AAA",
  ["E: AUG, P: GCU, A: UGG",
   "E: UGG, P: AAA, A: UAG",
   "E: ACC, P: AUG, A: GCU",
   "E: GCU, P: UGG, A: UAG"],
  "Translocation moves the ribosome one codon toward the 3' end: the tRNA on UGG (now holding the chain) moves to P, the empty tRNA on GCU moves to E, and the next codon, AAA, enters the A site.",
  "Translocation by one codon · Ribosomes move 5'→3'",
  ["translocation_one_codon", "ribosome_moves_5_to_3", "ribosome_a_p_e_sites"],
  points=2, diagram="ribosome_snapshot"),

combo(TP, "Endgame for this mRNA",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> The ribosome continues along the mRNA until it reaches UAG.<br><br><b>(나)</b> At that point, the tRNA in the P site holds the whole chain.",
  [S("When UAG reaches the A site, a release factor protein binds there instead of a tRNA.", True,
     "Stop codons are recognized by a protein release factor, not by a tRNA."),
   S("The chain is freed by breaking the peptide bond between its last two amino acids.", False,
     "Release breaks the bond between the finished chain and the tRNA holding it. All peptide bonds stay intact, and the last amino acid's carboxyl group becomes the C-terminus."),
   S("If UAG were mutated to UGA, the chain would run on past Lys, because UGA codes for an amino acid.", False,
     "UGA is also a stop codon (with UAA and UAG), so a release factor would still end the chain after Lys.")],
  "Termination: release factor · Stop codons · C-terminus",
  ["termination_release_factor", "start_stop_codons"],
  points=3, diagram="ribosome_snapshot"),

tf(TP, "Translation initiation differs between bacteria and eukaryotes.",
  "Because bacteria start translation differently (without a cap), they also use different stop codons to end it.",
  False,
  "Only initiation differs (cap and scanning vs Shine-Dalgarno sequences). Elongation and termination work the same way in both, ending at the same stop codons (UAA, UAG, UGA), where a release factor binds.",
  "Elongation and termination are shared · Stop codons",
  ["elongation_termination_conserved", "start_stop_codons"],
  points=1),

tf(TP, "Electron micrographs often show several ribosomes spaced along one mRNA at the same time.",
  "Each ribosome makes only part of the polypeptide, and the pieces are joined together afterward.",
  False,
  "Each ribosome starts at the start codon and runs to the stop codon, making its own complete chain. Several ribosomes on one mRNA simply make several copies at once.",
  "Many ribosomes per mRNA · Ribosomes read 5'→3'",
  ["gene_expression_overview_euk", "ribosome_moves_5_to_3", "translation_three_stages"],
  points=1),

tf(TP, "A mutation creates an extra AUG in the 5' untranslated region of a human mRNA, between the cap and the normal start codon, in a different reading frame.",
  "Scanning ribosomes can start at this new AUG instead, making a short, wrong polypeptide and less of the normal protein.",
  True,
  "Eukaryotic ribosomes start at the first AUG they reach while scanning from the cap. An upstream AUG in another frame diverts them into the wrong reading frame — a known cause of some inherited diseases.",
  "Scanning from the cap · Reading frame",
  ["euk_initiation_cap_scanning", "reading_frame"],
  points=2),

tf(TP, "A drug blocks only one step of translation: the large ribosomal subunit joining the small subunit at the start codon.",
  "Ribosomes already partway along an mRNA when the drug is added will finish their proteins, but no new proteins will be started.",
  True,
  "Joining of the large subunit is part of initiation. Ribosomes already in elongation don't need that step again, so they run on to the stop codon; new rounds of initiation are blocked.",
  "Three stages of translation",
  ["translation_three_stages", "euk_initiation_cap_scanning"],
  points=2),

mc(TP, "A mutation changes codon 40 of a gene's 300 codons (counting AUG as codon 1) into UAG. What does the cell make from this mRNA?",
  "A 39-amino-acid chain, freed when a release factor binds UAG",
  ["A full-length chain lacking only its 40th amino acid",
   "A 40-amino-acid chain ending in a special stop amino acid",
   "No chain at all, since translation can't begin",
   "A full-length chain, since a tRNA reads UAG as an amino acid"],
  "Codons 1–39 are translated normally. UAG in the A site is recognized by a release factor (no tRNA reads it), so a shortened 39-amino-acid chain is released — usually nonfunctional.",
  "Stop codons · Termination by release factor",
  ["termination_release_factor", "start_stop_codons"],
  points=2),

match(TP, "Where does it happen?",
  "Match each event to where it happens.",
  "Event", "Where",
  [("During elongation, a charged tRNA first pairs with its codon", "The A site"),
   ("The tRNA holding the growing chain waits for the next amino acid", "The P site"),
   ("An uncharged tRNA leaves the ribosome", "The E site"),
   ("A eukaryotic small subunit, with initiation factors, first binds an mRNA", "The 5' cap"),
   ("A bacterial ribosome first binds an mRNA", "AGGAGGU, upstream of an AUG")],
  "A = aminoacyl-tRNA entry, P = peptidyl-tRNA, E = exit. Eukaryotic initiation begins when the small subunit and initiation factors bind the 5' cap and scan to AUG; bacterial ribosomes bind Shine-Dalgarno sequences (AGGAGGU) just upstream of each AUG.",
  "A, P and E sites · Initiation in eukaryotes vs bacteria",
  ["ribosome_a_p_e_sites", "euk_initiation_cap_scanning", "prok_initiation_shine_dalgarno"],
  points=3),

# ───────────────────────── Regulation & Protein Sorting ─────────────────────────
combo(SO, "Four snapshots at the ER",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> Panels 1–4 follow one ribosome making one protein.<br><br><b>(나)</b> In panel 1, the SRP is bound to the signal sequence as it emerges from the ribosome.",
  [S("Translation pauses while the SRP is bound and resumes once the ribosome is handed to the channel.", True,
     "The SRP halts translation until the ribosome docks at the ER; when the SRP lets go, synthesis resumes and the chain is threaded through the channel."),
   S("The finished protein in panel 4 lacks the stretch of amino acids made first, including its starting Met.", True,
     "Chains are made N-terminus first, starting with Met, so the ER signal is the first segment out; cutting it off in the lumen removes the protein's original amino end."),
   S("To be secreted, the protein in panel 4 must first cross the ER membrane back into the cytosol.", False,
     "It never re-enters the cytosol: from the lumen it travels in vesicles through the Golgi and leaves by exocytosis (Module 3). Other lumen proteins stay in the ER or go to another organelle's lumen.")],
  "SRP targeting · Fates of rough-ER proteins (Module 3)",
  ["srp_er_targeting", "rough_er_protein_fates", "n_terminus_c_terminus", "m3_endomembrane_secretory_route"],
  points=3, diagram="srp_targeting_steps"),

mc(SO, "In a mutant cell the SRP receptor is missing, but the SRP and the signal sequence are normal. What happens to a protein destined for secretion?",
  "SRP still binds and pauses synthesis, but the ribosome can't dock at the ER",
  ["The SRP can't bind the signal sequence, so translation never pauses",
   "The protein enters the ER normally, since the channel alone recognizes the signal",
   "The protein enters the ER, but its signal sequence is never removed",
   "The protein is redirected to the mitochondria by its signal sequence"],
  "The SRP recognizes the signal and halts translation, but docking requires the SRP receptor on the ER membrane. Without it, the ribosome is never handed to the channel, so the protein doesn't enter the ER or follow the secretory route.",
  "SRP and SRP receptor · Translation starts in the cytosol",
  ["srp_er_targeting", "translation_starts_cytosol"],
  points=2, diagram="srp_targeting_steps"),

tf(SO, "A secretory protein's gene is altered so that its ER signal sequence is deleted; nothing else changes.",
  "The protein will be made on free ribosomes and stay in the cytosol, since the SRP has nothing to recognize.",
  True,
  "Translation always begins in the cytosol. Without a signal, the SRP never binds and the ribosome never goes to the ER; a protein with no signal remains in the cytosol.",
  "No signal → cytosol · SRP needs the signal sequence",
  ["sorting_signals_destinations", "srp_er_targeting", "translation_starts_cytosol"],
  points=1),

tf(SO, "The protein in the diagram has an ER signal sequence, which is cut off in panel 4.",
  "Deleting the 10 codons just before this protein's stop codon would stop it from entering the ER.",
  False,
  "The ER signal is the first part of the chain made, at the amino (N-terminal) end, where the SRP catches it as it emerges. The codons just before the stop codon encode the carboxyl (C-terminal) end, so deleting them leaves the signal, and entry into the ER, unaffected.",
  "Signal sequence at the N-terminus · Cleavage in the ER",
  ["srp_er_targeting", "n_terminus_c_terminus"],
  points=1, diagram="srp_targeting_steps"),

combo(SO, "Which end faces out?",
  "Using the diagram, which statements in <보기> are correct?",
  "<b>(가)</b> The protein's orientation in the ER membrane is set while it is being made.<br><br><b>(나)</b> It reaches the plasma membrane in vesicles that bud from one membrane and fuse with the next.",
  [S("In the right panel, the NH3+ end lies in the extracellular fluid.", True,
     "Budding and fusion never flip a membrane: the side facing the ER lumen stays inside the vesicles and faces outside the cell after fusion (Module 3). So the N-terminus, in the lumen, ends up outside."),
   S("The signal-anchor segment stays in the membrane because its side chains are mostly charged and cling to the phosphate heads.", False,
     "A segment spanning the membrane sits among the lipid tails, so its side chains are mostly nonpolar — the feature that marks integral membrane proteins (Module 3)."),
   S("The signal-anchor segment is cut off in the ER, as an ER signal sequence is, releasing the protein into the lumen.", False,
     "A signal-anchor sequence isn't removed: the channel releases it sideways into the membrane, where it anchors the protein for good.")],
  "Signal-anchor sequence · The lumen side becomes the outside (Module 3)",
  ["signal_anchor_membrane_protein", "rough_er_protein_fates", "m3_lumen_topology", "m3_membrane_protein_types"],
  points=3, diagram="signal_anchor_orientation"),

tf(SO, "A receptor is inserted into the ER membrane with its NH3+ end in the cytosol and its COO- end in the ER lumen, then reaches the plasma membrane by vesicle traffic. Kinases, enzymes in the cytosol, switch proteins on or off by adding phosphate groups to them.",
  "At the plasma membrane, a serine near this receptor's COO- end would be within reach of cytosolic kinases.",
  False,
  "Orientation is set when the protein is inserted into the ER, and budding and fusion never flip a membrane: the lumen side becomes the outside of the cell, while the cytosolic side stays cytosolic (Module 3). The COO- end, in the ER lumen, ends up outside the cell, out of the kinases' reach; only the NH3+ end stays in the cytosol.",
  "Membrane protein orientation (Module 3) · The lumen side becomes the outside",
  ["m3_lumen_topology"],
  points=2),

match(SO, "Address labels",
  "Match each protein to the sorting signal it needs.",
  "Protein", "Sorting signal",
  [("A glycolysis enzyme that works in the cytosol", "No signal sequence"),
   ("A citric acid cycle enzyme in the mitochondrial matrix", "An amino-terminal signal for organelle import (made on free ribosomes)"),
   ("A DNA polymerase that copies chromosomes", "An internal signal sequence"),
   ("Albumin, a blood protein secreted by liver cells", "An SRP-recognized ER signal, with no signal-anchor sequence"),
   ("A receptor that spans the plasma membrane", "An ER signal plus a signal-anchor sequence that keeps it in the membrane")],
  "Where a protein works decides its label: none for the cytosol; an amino-terminal signal for mitochondria or chloroplasts; an internal signal for the nucleus; an SRP-recognized amino-terminal signal for the ER and secretory route; and, for a protein that stays in a membrane, a signal-anchor sequence as well.",
  "Signal sequences and destinations",
  ["sorting_signals_destinations", "srp_er_targeting", "signal_anchor_membrane_protein", "translation_starts_cytosol"],
  points=3),

mc(SO, "Stomach cells secrete pepsin as an inactive precursor, pepsinogen, which becomes active only after part of its chain is cut off in the acidic stomach. Which level of gene-expression control does this illustrate?",
  "Post-translational modification",
  ["DNA accessibility",
   "Transcription factors",
   "RNA processing",
   "Translation initiation at the cap"],
  "The protein is already made; activating it by cutting the chain is a post-translational modification. Making it inactive protects the cells that produce it from digesting their own proteins.",
  "Post-translational modification · Real-world: digestive enzymes",
  ["post_translational_modification", "gene_expression_regulation_levels"],
  points=1),

tf(SO, "In a cell, gene Y's DNA is unpacked and its transcription factors are bound, so Y is transcribed at a high rate.",
  "How much active protein Y the cell contains can therefore be predicted from how fast gene Y is transcribed.",
  False,
  "Transcription is only one checkpoint. The transcript must still be processed and exported, and many proteins are made in an inactive form until they are cleaved or modified (for example, phosphorylated). Regulation at these later levels can keep active Y from appearing.",
  "Levels of gene regulation beyond transcription",
  ["gene_expression_regulation_levels", "post_translational_modification"],
  points=1),

combo(SO, "One gene, two cell types",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> In muscle cells, the gene for enzyme Z is wrapped tightly with histones and is never transcribed.<br><br><b>(나)</b> In liver cells, the gene is transcribed and enzyme Z is made in an inactive form, switched on when a kinase phosphorylates it as blood sugar drops.",
  [S("In muscle, expression of Z is blocked at the level of DNA accessibility.", True,
     "Tightly packed DNA can't be reached by the transcription machinery, so the gene stays silent."),
   S("In liver, phosphorylation switches Z on by changing its amino acid sequence.", False,
     "Adding a phosphate group is a post-translational modification: the shape and activity change, but the amino acid sequence stays the same."),
   S("In liver, a drug that blocks the kinase would leave enzyme Z inactive even though Z's mRNA is still made.", True,
     "Phosphorylation is the switch that activates Z after translation; without the kinase, Z is made but stays in its inactive form.")],
  "Levels of gene regulation · Post-translational modification",
  ["gene_expression_regulation_levels", "post_translational_modification"],
  points=3),

tf(SO, "Electron micrographs of a pancreatic cell show some ribosomes free in the cytosol and others bound to the rough ER.",
  "A ribosome making a secreted protein is already bound to the ER when it starts translating, since the ER is where that protein is headed.",
  False,
  "Every mRNA starts being translated on a ribosome in the cytosol. Only when the ER signal sequence emerges does the SRP bind it and bring the ribosome to the ER; free and ER-bound ribosomes are the same kind, differing only in what they are making.",
  "Translation starts in the cytosol · SRP targeting",
  ["translation_starts_cytosol", "srp_er_targeting", "gene_expression_overview_euk"],
  points=1),
]

for _c in CARDS:
    _c["mod"] = MOD
