from cardkit import S, combo, match, tf, mc

MOD = 0
BR = "Connecting Modules 1–6"

CARDS = [
combo(BR, "Is every catalyst a protein?",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Module 6: chemical reactions in cells are catalyzed by proteins called enzymes.<br><br><b>(나)</b> Module 5: the peptidyl transferase center that forms each peptide bond is made of rRNA.",
  [S("(나) shows that at least one biological catalyst is an RNA molecule rather than a protein.", True,
     "The catalytic heart of the ribosome is rRNA, so 'enzymes are proteins' has an important exception (catalytic RNAs are called ribozymes)."),
   S("Like a protein enzyme, the rRNA catalyst speeds peptide bond formation by lowering its activation energy, without changing its ΔG.", True,
     "Every catalyst works by lowering the barrier to the transition state; none changes the free-energy difference between reactants and products."),
   S("Because the peptidyl transferase is made of RNA, the bonds it forms between amino acids are phosphodiester bonds, like those in RNA itself (Module 2).", False,
     "A catalyst doesn't change its product: the ribosome still joins the carboxyl group of one amino acid to the amino group of the next, forming a peptide (amide) bond. Phosphodiester bonds link nucleotides.")],
  "Ribozymes · Catalysts lower activation energy · Peptide vs phosphodiester bonds (Module 2)",
  ["ribosome_rna_protein_subunits", "enzyme_lowers_ea_not_delta_g", "peptide_bond_dehydration", "m2_functional_groups"],
  points=3),

tf(BR, "A protein made of two chains, 60 and 40 amino acids long, joined by one disulfide bond, is digested completely into free amino acids.",
  "Breaking its peptide bonds by hydrolysis uses up 98 water molecules (Module 2).",
  True,
  "A chain of n amino acids has n − 1 peptide bonds: 59 + 39 = 98. Each was made by releasing one H2O and each hydrolysis consumes one (Module 2). The disulfide bond between the chains joins side chains, so it isn't a peptide bond.",
  "Peptide bonds and hydrolysis (Module 2) · Disulfides aren't peptide bonds",
  ["peptide_bond_dehydration", "cysteine_disulfide", "m2_condensation_hydrolysis"],
  points=1),

tf(BR, "Stomach acid has a pH of about 2. At low pH, ionizable groups pick up H+ (Module 2).",
  "At pH 2, a free alanine molecule (side chain –CH3) carries a net positive charge, because its carboxyl group is mostly protonated (–COOH) while its amino group stays –NH3+.",
  True,
  "Alanine's only ionizable groups are the amino and carboxyl groups every amino acid carries on its α carbon; its –CH3 side chain has no charge. At physiological pH it carries H3N+ and COO- (no net charge). Lowering the pH adds H+ to the carboxylate and removes its negative charge, so mainly the +1 on the amino group remains.",
  "Amino acid charges · pH and ionization (Module 2)",
  ["aa_charged_physiological_ph", "aa_four_groups_alpha_carbon", "m2_ph_ionization_groups"],
  points=2),

tf(BR, "A folded protein is held together by many hydrogen bonds, ionic bonds and van der Waals contacts, plus a few disulfide bonds.",
  "Because each noncovalent contact is weak, together they contribute little; the disulfide bonds do almost all the work of holding the shape.",
  False,
  "Each weak interaction is far weaker than a covalent bond (Module 2), but a folded protein has hundreds of them, and together they hold the fold. Many proteins have no disulfide bonds at all.",
  "Weak bonds add up (Module 2) · Tertiary interactions",
  ["tertiary_r_group_interactions", "m2_bond_strengths"],
  points=1),

combo(BR, "One gene, two hosts",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> E. coli (Module 1) has no nucleus, and its mRNAs have no 5' cap.<br><br><b>(나)</b> Human mRNAs are capped and processed in the nucleus before export (Module 4).",
  [S("A human gene placed in E. coli needs a Shine-Dalgarno-type sequence upstream of its AUG to be translated efficiently.", True,
     "Bacterial ribosomes find start codons by pairing with Shine-Dalgarno sequences, not caps, so a bacterial ribosome-binding sequence must be supplied."),
   S("An E. coli ribosome must wait until transcription of an mRNA is complete before it can begin translating it.", False,
     "With no nuclear envelope in the way, bacterial ribosomes start on the 5' end of an mRNA while RNA polymerase is still making the rest (Module 4)."),
   S("Antibiotics that block bacterial ribosomes should block human cytosolic ribosomes just as well, since both have A, P and E sites.", False,
     "Both share the same stages and sites, but bacterial ribosomes are smaller and structurally different; many antibiotics exploit those differences and spare human cytosolic ribosomes.")],
  "Translation in prokaryotes vs eukaryotes (Modules 1, 4, 5)",
  ["prok_initiation_shine_dalgarno", "elongation_termination_conserved", "ribosome_rna_protein_subunits", "m1_prok_euk_differences", "m4_coupled_transcription_translation"],
  points=3),

tf(BR, "A test tube holds a viral mRNA, free amino acids, ATP, GTP and purified ribosomes, but no viral protein is made.",
  "The missing ingredients are host-cell parts such as tRNAs, aminoacyl tRNA synthetases and translation factors, which a virus doesn't make for itself (Module 1).",
  True,
  "Translation needs more than ribosomes: tRNAs, synthetases to charge them, and initiation, elongation and release factors. Viruses have genes but no translation machinery or metabolism of their own (Module 1), so inside a cell they borrow all of these from the host.",
  "Components of translation · Viruses aren't cells (Module 1)",
  ["translation_components", "m1_virus_not_cell"],
  points=1),

tf(BR, "Euglena, a single-celled protist, photosynthesizes in the light; kept in the dark, it absorbs organic molecules from the water for both energy and carbon.",
  "In the dark, Euglena belongs in the same cell of the diagram as fungi (Module 1).",
  True,
  "In the dark Euglena gets energy and carbon from organic molecules: cell D, the chemoheterotrophs. Fungi are heterotrophs that absorb organic molecules for both energy and carbon (Module 1), so they belong in D too. In the light, Euglena moves to A (photoautotroph).",
  "Metabolic classes · Protist nutrition (Module 1)",
  ["metabolic_classification_examples", "phototroph_vs_chemotroph", "autotroph_vs_heterotroph", "m1_kingdom_nutrition"],
  points=2, diagram="metabolic_classification_grid"),

tf(BR, "Enzymes called kinases switch many proteins on or off by attaching a phosphate group to the –OH of a serine side chain.",
  "This adds negative charge where a neutral polar side chain used to be, which can change the protein's shape or what it binds.",
  True,
  "A phosphate group is ionized at physiological pH (Module 2), so phosphorylation turns a polar, uncharged side chain into a negatively charged one. New ionic attractions and repulsions can reshape the protein — a post-translational switch.",
  "Post-translational modification · Phosphate groups are charged (Module 2)",
  ["post_translational_modification", "acidic_basic_charged_ionic", "m2_functional_groups"],
  points=1),

tf(BR, "A tRNA is a single RNA strand of 70–90 nucleotides folded into a cloverleaf.",
  "A mutation that changes one base in a stem, so it can no longer pair with its partner, would weaken the cloverleaf even though the covalent backbone is unchanged (Module 2).",
  True,
  "The stems form when complementary stretches of the single strand pair (A–U, G–C) through hydrogen bonds. Losing one pair removes some of those weak bonds and loosens the fold, while the covalent backbone that holds the chain together is untouched.",
  "tRNA structure · Weak vs covalent bonds (Module 2)",
  ["trna_adapter_structure", "m2_bond_strengths"],
  points=1),

combo(BR, "What it costs to build a protein",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Each amino acid is attached to its tRNA by a synthetase that spends ATP.<br><br><b>(나)</b> Joining amino acids is a condensation reaction (Module 2).",
  [S("Building a protein is anabolic: it forms new bonds between monomers and needs an energy input.", True,
     "Assembling a polymer from monomers is anabolism, and it is endergonic overall."),
   S("Peptide bond formation is strongly exergonic on its own, which is why making proteins needs no ATP.", False,
     "Joining amino acids by condensation needs energy — it's the reverse of exergonic hydrolysis (Module 2). Cells pay with the ATP spent charging tRNAs."),
   S("Spending ATP to charge tRNAs couples an exergonic reaction to the endergonic job of joining amino acids, making the overall process favourable.", True,
     "Energy from ATP hydrolysis is stored in the bond between the amino acid and its tRNA and released when the peptide bond forms — energetic coupling.")],
  "Anabolism · Energetic coupling · Condensation (Module 2)",
  ["anabolism_vs_catabolism", "energetic_coupling_atp", "aminoacyl_trna_synthetase_charging", "m2_condensation_hydrolysis"],
  points=3),

mc(BR, "The Na+/K+ pump (Module 3) uses about a third of a resting cell's ATP. Where does the energy released by that ATP go?",
  "Part is stored in the ion gradients and part is released as heat",
  ["It stays in the pump protein's phosphate bond until the next cycle",
   "It becomes kinetic energy that keeps the pumped ions moving outward",
   "It is used up and destroyed as the ions are pushed uphill",
   "It flows straight back into ATP whenever the ions leak back"],
  "Pushing ions up their gradients stores potential energy (Module 3), but no energy conversion is 100% efficient (second law), so some of ATP's energy is released as heat. None is destroyed (first law).",
  "First and second laws · Gradients store energy (Module 3)",
  ["first_law_conservation", "second_law_direction_entropy", "potential_vs_kinetic_energy", "m3_active_transport_atp"],
  points=2),

tf(BR, "Histones (Module 4) are proteins that package DNA inside the nucleus.",
  "They reach the nucleus in vesicles budding from the rough ER, like proteins headed for secretion.",
  False,
  "Histones are made on free ribosomes in the cytosol and carry an internal signal sequence that directs their active import through the nuclear pores (Module 3). The ER and vesicle route serves secreted and endomembrane proteins; it doesn't deliver proteins into the nucleus.",
  "Internal signal → nucleus · Nuclear pores (Module 3)",
  ["sorting_signals_destinations", "translation_starts_cytosol", "m3_nuclear_pores_transport"],
  points=1),

match(BR, "Module 2 chemistry, Module 5–6 jobs",
  "Match each event to the bond, interaction or reaction (from Module 2) behind it.",
  "Event", "Bond or reaction",
  [("Joining two amino acids on the ribosome", "A peptide (amide) bond formed by condensation"),
   ("A lysine and a glutamate side chain holding two parts of a fold together", "An ionic bond between opposite charges"),
   ("A codon pairing with an anticodon", "Hydrogen bonds between complementary bases"),
   ("ATP releasing energy to power a pump", "Hydrolysis of a bond between phosphate groups"),
   ("Holding an α helix in its coil", "Hydrogen bonds between backbone C=O and N–H groups")],
  "The same few bond types do every job: condensation builds peptide bonds; opposite charges on side chains form ionic bonds; complementary bases hydrogen-bond in nucleic acids; hydrolysis splits ATP's phosphate bonds; and backbone C=O and N–H groups hydrogen-bond in secondary structure.",
  "Bond types (Module 2) across Modules 5–6",
  ["peptide_bond_dehydration", "acidic_basic_charged_ionic", "atp_phosphate_bonds_energy", "secondary_backbone_hbonds_only", "m2_condensation_hydrolysis"],
  points=3),

mc(BR, "Most cases of achondroplasia, the most common form of dwarfism, come from one base change in the FGFR3 gene: codon 380 changes from GGG to AGG on the nontemplate strand. Using the genetic code table, what happens to the protein?",
  "mRNA codon GGG becomes AGG, so Arg replaces Gly",
  ["mRNA codon CCC becomes UCC, so Ser replaces Pro",
   "mRNA codon GGG becomes AGG, which ribosomes can't read",
   "The reading frame shifts, changing every later amino acid",
   "Nothing, since the genetic code is redundant"],
  "The mRNA matches the nontemplate strand with U for T (Module 4): GGG (Gly) → AGG (Arg). A single substitution changes one codon and one amino acid without shifting the frame, and it isn't silent, because AGG codes for a different amino acid.",
  "Nontemplate strand → mRNA (Module 4) · Reading the code · Real-world: achondroplasia",
  ["codon_triplet_nonoverlapping", "genetic_code_64_redundant", "m4_template_coding_strands"],
  points=2, diagram="genetic_code_table"),

combo(BR, "From frying pan to stomach",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Cooking a piece of fish unfolds (denatures) its proteins.<br><br><b>(나)</b> In the stomach, the enzyme pepsin hydrolyzes their peptide bonds, working best near pH 2.",
  [S("Denatured proteins are easier for pepsin to cut, because unfolding exposes peptide bonds that were buried inside the fold.", True,
     "An unfolded chain gives the enzyme's active site access to more of the backbone — one reason cooked protein is easier to digest."),
   S("Pepsin is itself a protein, so in the small intestine it is eventually digested too.", True,
     "Pepsin is inactivated at the intestine's higher pH, and its peptide bonds are hydrolyzed by intestinal protein-digesting enzymes."),
   S("Pepsin speeds digestion only by lowering the activation energy of peptide-bond hydrolysis, which is already exergonic as the reverse of condensation (Module 2).", True,
     "Hydrolysis is the reverse of the energy-requiring condensation that formed the peptide bond, so it is favourable on its own; pepsin just makes it fast, without changing ΔG.")],
  "Denaturation · Hydrolysis (Module 2) · Enzymes are proteins · Digestion",
  ["enzymes_are_proteins_active_site", "enzyme_lowers_ea_not_delta_g", "m2_condensation_hydrolysis"],
  points=3),

tf(BR, "During a high fever, body temperature rises from 37°C to about 41°C.",
  "Because molecules move faster when warmer, the higher a fever climbs, the faster the body's enzymes can work.",
  False,
  "Up to a point, more kinetic energy speeds reactions. But extra heat also disrupts the weak hydrogen bonds and other interactions that hold an enzyme's fold (Module 2); some enzymes start to unfold and lose activity at high temperatures.",
  "Temperature, kinetic energy and protein folding (Modules 2, 5, 6)",
  ["tertiary_r_group_interactions", "enzymes_are_proteins_active_site", "activation_energy_transition_state", "m2_bond_strengths"],
  points=1),

combo(BR, "Supplying the mitochondria",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Mitochondria have their own DNA and bacteria-like ribosomes (Module 3).<br><br><b>(나)</b> Most mitochondrial proteins are nonetheless encoded by genes in the nucleus (Module 5).",
  [S("Nuclear-encoded mitochondrial proteins are made on free ribosomes in the cytosol and carry an amino-terminal signal for import.", True,
     "Proteins for mitochondria and chloroplasts are made in the cytosol and directed by an amino-terminal signal sequence."),
   S("Proteins encoded by mitochondrial DNA are made in the cytosol and then imported, using an amino-terminal signal.", False,
     "Genes in mitochondrial DNA are transcribed and translated inside the mitochondrion, on its own bacteria-like ribosomes (Module 3); only nuclear-encoded proteins need importing."),
   S("Attaching a mitochondrial protein's amino-terminal signal to a normally cytosolic protein would send that protein into mitochondria.", True,
     "The signal sequence is the address label: moved onto another protein, it directs that protein to the mitochondria instead.")],
  "Sorting to mitochondria · Semi-autonomous organelles (Module 3)",
  ["sorting_signals_destinations", "translation_starts_cytosol", "m3_mito_chloro_semi_autonomous"],
  points=3),

tf(BR, "Mature human red blood cells have lost their nucleus and their ribosomes.",
  "They therefore can't replace damaged hemoglobin, since making new protein requires ribosomes to translate mRNA.",
  True,
  "No ribosomes means no translation (and no nucleus means no new mRNA). A red blood cell works with the hemoglobin it was built with and is replaced after about 120 days.",
  "Ribosomes are required for translation · Cell structure and function (Module 1)",
  ["translation_components", "ribosome_rna_protein_subunits", "m1_cell_structure_function"],
  points=1),

combo(BR, "The same push from water",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Phospholipid tails cluster in the interior of the bilayer (Module 3).<br><br><b>(나)</b> Nonpolar side chains cluster in the interior of a folded protein (Module 5).",
  [S("Both clusterings are driven mainly by water molecules hydrogen-bonding with one another and excluding nonpolar groups (Module 2).", True,
     "Water's network of hydrogen bonds pushes nonpolar groups together; the attraction between the nonpolar groups themselves is weak."),
   S("Both are held together by covalent bonds between neighbouring nonpolar groups.", False,
     "No covalent bonds join the tails or the clustered side chains; the clusters can rearrange, which is why membranes are fluid."),
   S("Mild detergents can pull an integral membrane protein out of the bilayer still folded, because their nonpolar tails coat its membrane-spanning segment (Module 3).", True,
     "The membrane-spanning segment's side chains are mostly nonpolar. Mild detergent tails cover them while the polar heads face water, standing in for the lipids — how membrane proteins are extracted for study. Harsh detergents such as SDS unfold proteins instead.")],
  "Hydrophobic effect (Module 2) · Bilayers (Module 3) · Protein folding (Module 5)",
  ["hydrophobic_aa_buried_vdw", "m2_hydrophobic_effect_water", "m3_membrane_protein_types"],
  points=3),

tf(BR, "RNA polymerase adds each nucleotide using energy from the incoming nucleoside triphosphate, releasing pyrophosphate (Module 4).",
  "This is energetic coupling: splitting off pyrophosphate is exergonic and drives the endergonic formation of a phosphodiester bond.",
  True,
  "Forming a phosphodiester bond by condensation needs energy; breaking the phosphate–phosphate bond of the incoming triphosphate releases it. The two steps are linked, so the net ΔG is negative — the same strategy ATP-driven reactions use.",
  "Energetic coupling · Nucleotide polymerization (Module 4)",
  ["energetic_coupling_atp", "atp_phosphate_bonds_energy", "m4_ntp_energy_polymerization", "m2_condensation_hydrolysis"],
  points=2),

tf(BR, "During a long fast, fat cells break their stored triacylglycerols (fats) into glycerol and fatty acids, which other tissues then use for energy.",
  "Unlike glycogen, a triacylglycerol isn't a polymer built from repeating monomers, and breaking it down this way counts as catabolism.",
  True,
  "Both parts hold. Catabolism is the breakdown of molecules into smaller units, releasing energy, and the notes' figure on anabolism and catabolism includes lipids → fatty acids. And unlike glycogen, a chain of glucose monomers, a triacylglycerol is glycerol plus three fatty acids, not a repeating chain: lipids are the only macromolecule that isn't a polymer (Module 2).",
  "Catabolism · Lipids aren't polymers (Module 2) · Real-world: fasting",
  ["anabolism_vs_catabolism", "m2_macromolecule_monomers"],
  points=1),

mc(BR, "Becker and Duchenne muscular dystrophy are often caused by deletions in the dystrophin gene. In patient A, the missing exon held 150 nucleotides of coding sequence; in patient B, it held 151. A has mild Becker disease and makes a shorter but partly working dystrophin; B has severe Duchenne disease. Which explanation fits best?",
  "A loses a multiple of 3 nucleotides and keeps its frame; B's frame shifts",
  ["B loses one more nucleotide than A, so its protein is just one amino acid shorter",
   "Only B's deletion removes the start codon, so no translation can begin at all",
   "A's deletion is silent because the code is redundant, but B's deletion is not",
   "B's exon held the stop codon, so its ribosomes run off the end of the mRNA"],
  "A missing exon simply drops its nucleotides from the spliced mRNA (Module 4). 150 is a multiple of 3, so after the gap A's ribosomes keep reading in the normal frame: the protein lacks about 50 amino acids but still partly works. 151 is not, so every codon after B's gap is read in the wrong frame, and a stop codon soon ends the chain.",
  "Reading frame · Nonoverlapping triplets · Exons and splicing (Module 4) · Real-world: muscular dystrophy",
  ["reading_frame", "codon_triplet_nonoverlapping", "m4_mrna_processing_cap_tail_splicing"],
  points=2),

combo(BR, "An antibiotic that garbles proteins",
  "Which statements in <보기> are correct?",
  "<b>(가)</b> Streptomycin binds the small subunit of bacterial ribosomes and makes them misread codons.<br><br><b>(나)</b> In bacteria, genes are transcribed by RNA polymerase and translated by ribosomes (Module 4).",
  [S("Misreading puts wrong amino acids at scattered positions, producing many misfolded, nonfunctional proteins.", True,
     "A wrong codon–anticodon match inserts the wrong amino acid; changed primary structure can derail folding across the cell's proteins."),
   S("The bacterium's mRNAs would carry altered codons, since the drug changes the genetic message.", False,
     "The mRNAs are transcribed normally from the DNA; the drug acts on ribosomes, making them misread correct codons."),
   S("Because codons are read in triplets, each misreading shifts the reading frame for the rest of the protein.", False,
     "Misreading a codon substitutes one amino acid; the ribosome still moves three bases at a time, so the frame is kept.")],
  "Ribosome accuracy · Reading frame · Transcription vs translation (Module 4)",
  ["reading_frame", "sequence_determines_folding", "m4_central_dogma_flow"],
  points=3),

tf(BR, "In a polypeptide backbone, the O of each C=O and the N of each N–H are more electronegative than the atoms they're bonded to (Module 2).",
  "This polarity is what allows a C=O of one residue and an N–H of another to form the hydrogen bonds of helices and sheets.",
  True,
  "Electronegative O and N pull electrons toward themselves, giving the O a partial negative charge and the H on N a partial positive charge — the ingredients of a hydrogen bond (Module 2). Secondary structure is built from these backbone H-bonds.",
  "Electronegativity and H-bonds (Module 2) · Secondary structure",
  ["secondary_backbone_hbonds_only", "m2_electronegativity_polarity"],
  points=1),

match(BR, "Where in the cell?",
  "Match each event to where it happens in a human cell.",
  "Event", "Location",
  [("Adding a 5' cap to a primary transcript", "Nucleus"),
   ("Charging tRNAs with their amino acids", "Cytosol"),
   ("Translating the mRNA for a secreted protein once SRP has docked", "Ribosomes on the rough ER"),
   ("Cutting off the signal sequence of a secreted protein", "ER lumen side of the ER membrane"),
   ("Moving the finished mRNA out to the cytosol", "Nuclear pores")],
  "RNA processing happens in the nucleus, and the finished mRNA leaves through nuclear pores (Module 3); tRNA charging and the start of translation of nuclear-encoded mRNAs happen in the cytosol; SRP moves a secretory protein's translation to the rough ER, where the signal sequence is removed on the lumen side.",
  "Where each step of gene expression happens (Modules 3, 4, 5)",
  ["translation_starts_cytosol", "srp_er_targeting", "gene_expression_overview_euk", "m3_nuclear_pores_transport", "m4_mrna_processing_cap_tail_splicing"],
  points=3),

tf(BR, "Module 1 lists acquiring and using energy as a property of every cell, including plant cells.",
  "Even a photoautotroph's cells need ATP, because light cannot directly power processes such as protein synthesis.",
  True,
  "Light energy is first captured as chemical energy (ATP and sugars). ATP is the currency that actually drives cellular work everywhere in the plant, including root cells that never see light.",
  "ATP as universal currency · Cells acquire and use energy (Module 1)",
  ["cells_need_energy_work", "atp_energy_currency", "m1_cell_property_energy"],
  points=1),

mc(BR, "If a cell's Na+/K+ pumps stop (Module 3), its Na+ gradient runs down within minutes. Which principle explains why the gradient doesn't simply stay put?",
  "Spontaneous change runs downhill in energy, toward more disorder",
  ["Energy can be neither created nor destroyed, only converted to new forms",
   "Enzymes lower the activation energy that a reaction has to overcome",
   "A reaction run in reverse has a ΔG of the same size but opposite sign",
   "Coupled reactions must share an intermediate, such as a phosphate"],
  "A gradient is an ordered, high-energy state, and the second law says events run from higher to lower energy and toward more disorder, so ions leak back until the gradient is gone. The other statements are true principles, but none explains why the gradient runs down; only continual pumping, paid for with ATP, holds it in place.",
  "Second law · Gradients store potential energy (Module 3)",
  ["second_law_direction_entropy", "m3_active_transport_atp"],
  points=2),
]

for _c in CARDS:
    _c["mod"] = MOD
